/**
 * Configurações públicas da ZikaShop — sem "use server"
 * Pode ser importado tanto em client quanto em server components.
 */

export const SUGGESTED_PRICES: Record<string, Record<string, number>> = {
  TITLE:           { COMMON:   50, UNCOMMON:  120, RARE:   250, EPIC:   500, LEGENDARY: 1000 },
  BANNER:          { COMMON:   80, UNCOMMON:  200, RARE:   400, EPIC:   800, LEGENDARY: 1500 },
  FRAME:           { COMMON:  100, UNCOMMON:  250, RARE:   500, EPIC:  1000, LEGENDARY: 2000 },
  ZIKALOOT_TICKET: { COMMON:  150, UNCOMMON:  150, RARE:   150, EPIC:   150, LEGENDARY:  150 },
  EGG_COMMON:      { COMMON:  600, UNCOMMON:  600, RARE:   600, EPIC:   600, LEGENDARY:  600 },
  EGG_RARE:        { COMMON: 3400, UNCOMMON: 3400, RARE:  3400, EPIC:  3400, LEGENDARY: 3400 },
  EGG_SPECIAL:     { COMMON: 6750, UNCOMMON: 6750, RARE:  6750, EPIC:  6750, LEGENDARY: 6750 },
  EGG_LAB:         { COMMON: 12000, UNCOMMON: 12000, RARE: 12000, EPIC: 12000, LEGENDARY: 12000 },
  EGG_EVENT:       { COMMON:    0, UNCOMMON:    0, RARE:     0, EPIC:     0, LEGENDARY:    0 },
  EGG_GEN1:        { COMMON: 1800, UNCOMMON: 1800, RARE:  1800, EPIC:  1800, LEGENDARY: 1800 },
  EGG_GEN2:        { COMMON: 1800, UNCOMMON: 1800, RARE:  1800, EPIC:  1800, LEGENDARY: 1800 },
  EGG_GEN3:        { COMMON: 2000, UNCOMMON: 2000, RARE:  2000, EPIC:  2000, LEGENDARY: 2000 },
  EGG_GEN4:        { COMMON: 2000, UNCOMMON: 2000, RARE:  2000, EPIC:  2000, LEGENDARY: 2000 },
  EGG_GEN5:        { COMMON: 2000, UNCOMMON: 2000, RARE:  2000, EPIC:  2000, LEGENDARY: 2000 },
  EGG_GEN6:        { COMMON: 2200, UNCOMMON: 2200, RARE:  2200, EPIC:  2200, LEGENDARY: 2200 },
  EGG_GEN7:        { COMMON: 2200, UNCOMMON: 2200, RARE:  2200, EPIC:  2200, LEGENDARY: 2200 },
  EGG_GEN8:        { COMMON: 2200, UNCOMMON: 2200, RARE:  2200, EPIC:  2200, LEGENDARY: 2200 },
  EGG_GEN9:        { COMMON: 2200, UNCOMMON: 2200, RARE:  2200, EPIC:  2200, LEGENDARY: 2200 },
  EGG_GEN6PLUS:    { COMMON: 2400, UNCOMMON: 2400, RARE:  2400, EPIC:  2400, LEGENDARY: 2400 },
  MASCOT_FOOD:     { COMMON:   35, UNCOMMON:   35, RARE:    35, EPIC:    35, LEGENDARY:   35 },
  MASCOT_SWEET:    { COMMON:  100, UNCOMMON:  100, RARE:   100, EPIC:   100, LEGENDARY:  100 },
  MASCOT_BUFF_EXP:   { COMMON: 750, UNCOMMON: 750, RARE: 750, EPIC: 750, LEGENDARY: 750 },   // Vitamina Chocante
  MASCOT_BUFF_STAT:  { COMMON: 4500, UNCOMMON: 4500, RARE: 4500, EPIC: 4500, LEGENDARY: 4500 }, // Proteína Zika
  MASCOT_BUFF_HAPPY: { COMMON: 300, UNCOMMON: 300, RARE: 300, EPIC: 300, LEGENDARY: 300 },   // Bala de Mel
  MASCOT_BUFF_LUCK:  { COMMON: 1200, UNCOMMON: 1200, RARE: 1200, EPIC: 1200, LEGENDARY: 1200 }, // Amuleto da Sorte
  MASCOT_BUFF_MOOD:  { COMMON: 150, UNCOMMON: 150, RARE: 150, EPIC: 150, LEGENDARY: 150 },   // Água Fresca
  LUCKY_EGG:       { COMMON: 1600, UNCOMMON: 1600, RARE: 1600, EPIC: 1600, LEGENDARY: 1600 },
  WEAKNESS_POLICY: { COMMON:  600, UNCOMMON:  600, RARE:  600, EPIC:  600, LEGENDARY:  600 },
  PICNIC_BASKET:   { COMMON: 3500, UNCOMMON: 3500, RARE: 3500, EPIC: 3500, LEGENDARY: 3500 },
  VACATION_TICKET: { COMMON: 2000, UNCOMMON: 2000, RARE: 2000, EPIC: 2000, LEGENDARY: 2000 },
  XP_SHARE:        { COMMON: 8000, UNCOMMON: 8000, RARE: 8000, EPIC: 8000, LEGENDARY: 8000 },
  RAINBOW_FEATHER: { COMMON: 10000, UNCOMMON: 10000, RARE: 10000, EPIC: 10000, LEGENDARY: 10000 },
  SYNC_TICKET_FIRE_LEFT:   { COMMON: 0, UNCOMMON: 0, RARE: 0, EPIC: 0, LEGENDARY: 0 },
  SYNC_TICKET_WATER_RIGHT: { COMMON: 0, UNCOMMON: 0, RARE: 0, EPIC: 0, LEGENDARY: 0 },
  SYNC_TICKET_COMPLETE:    { COMMON: 0, UNCOMMON: 0, RARE: 0, EPIC: 0, LEGENDARY: 0 },
};

export const EGG_SHOP_ITEM_TYPES = [
  "EGG_COMMON",
  "EGG_RARE",
  "EGG_SPECIAL",
  "EGG_LAB",
  "EGG_GEN1",
  "EGG_GEN2",
  "EGG_GEN3",
  "EGG_GEN4",
  "EGG_GEN5",
  "EGG_GEN6",
  "EGG_GEN7",
  "EGG_GEN8",
  "EGG_GEN9",
  "EGG_GEN6PLUS",
] as const;

export const MASCOT_FOOD_SHOP_ITEM_TYPES = [
  "MASCOT_FOOD",
  "MASCOT_SWEET",
] as const;

export const MASCOT_BUFF_SHOP_ITEM_TYPES = [
  "MASCOT_BUFF_EXP",
  "MASCOT_BUFF_STAT",
  "MASCOT_BUFF_HAPPY",
  "MASCOT_BUFF_LUCK",
  "MASCOT_BUFF_MOOD",
] as const;

export const SPECIAL_MASCOT_SHOP_ITEM_TYPES = [
  "LUCKY_EGG",
  "WEAKNESS_POLICY",
  "PICNIC_BASKET",
  "VACATION_TICKET",
  "XP_SHARE",
  "RAINBOW_FEATHER",
] as const;

export const EVENT_SHOP_ITEM_TYPES = [
  "SYNC_TICKET_FIRE_LEFT",
  "SYNC_TICKET_WATER_RIGHT",
  "SYNC_TICKET_COMPLETE",
] as const;

// Itens que só podem existir uma vez no inventário do jogador.
// Ao tentar ganhar/comprar um segundo exemplar, ele é automaticamente vendido pela metade do preço.
export const UNIQUE_ITEM_TYPES: ReadonlySet<string> = new Set(["XP_SHARE"]);

export const MASCOT_SHOP_ITEM_TYPES = [
  ...EGG_SHOP_ITEM_TYPES,
  ...MASCOT_FOOD_SHOP_ITEM_TYPES,
  ...MASCOT_BUFF_SHOP_ITEM_TYPES,
  ...SPECIAL_MASCOT_SHOP_ITEM_TYPES,
] as const;

export const CONSUMABLE_SHOP_ITEM_TYPES = [
  "ZIKALOOT_TICKET",
  ...MASCOT_SHOP_ITEM_TYPES,
] as const;

export const SHOP_ITEM_EMOJI: Record<string, string> = {
  ZIKALOOT_TICKET: "🎟️",
  EGG_LAB: "🧪🥚",
  EGG_EVENT: "⭐🥚",
  MASCOT_FOOD: "🍖",
  MASCOT_SWEET: "🍬",
  MASCOT_BUFF_EXP: "⚡",
  MASCOT_BUFF_STAT: "💊",
  MASCOT_BUFF_HAPPY: "🍯",
  MASCOT_BUFF_LUCK: "🍀",
  MASCOT_BUFF_MOOD: "💧",
  LUCKY_EGG: "🥚✨",
  WEAKNESS_POLICY: "🛡️",
  PICNIC_BASKET: "🧺",
  VACATION_TICKET: "🏖️",
  XP_SHARE: "📡",
  RAINBOW_FEATHER: "🌈",
};

export function getShopItemEmoji(type: string): string {
  return SHOP_ITEM_EMOJI[type] ?? "📦";
}

export const EGG_SHOP_TO_EGG_TYPE: Record<string, string> = {
  EGG_COMMON: "COMMON",
  EGG_RARE: "RARE",
  EGG_SPECIAL: "SPECIAL",
  EGG_LAB: "LAB",
  EGG_EVENT: "EVENT",
  EGG_GEN1: "EGG_GEN1",
  EGG_GEN2: "EGG_GEN2",
  EGG_GEN3: "EGG_GEN3",
  EGG_GEN4: "EGG_GEN4",
  EGG_GEN5: "EGG_GEN5",
  EGG_GEN6: "EGG_GEN6",
  EGG_GEN7: "EGG_GEN7",
  EGG_GEN8: "EGG_GEN8",
  EGG_GEN9: "EGG_GEN9",
  EGG_GEN6PLUS: "EGG_GEN6PLUS",
};

export function isEggShopItemType(type: string): boolean {
  return EGG_SHOP_ITEM_TYPES.includes(type as typeof EGG_SHOP_ITEM_TYPES[number]);
}

export function isMascotShopItemType(type: string): boolean {
  return MASCOT_SHOP_ITEM_TYPES.includes(type as typeof MASCOT_SHOP_ITEM_TYPES[number]);
}

export function isConsumableShopItemType(type: string): boolean {
  return CONSUMABLE_SHOP_ITEM_TYPES.includes(type as typeof CONSUMABLE_SHOP_ITEM_TYPES[number]);
}

export function getSuggestedPrice(type: string, rarity: string): number {
  return SUGGESTED_PRICES[type]?.[rarity] ?? 100;
}
