"use client";
import { useTransition } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { resolveArenaDraftBattleAction, submitArenaDraftAction } from "../actions";
type Pet={id:string;speciesId:number;name:string;sprite:string;types:string[];isMega:boolean;disabled:boolean};
type Battle={result?:string;rounds?:number;events?:Array<{turn:number;actorName:string;targetName:string;action:string;damage:number;effect?:string}>}|null;
export function DraftRoomClient({matchId,state,turn,ownSide,own,rival,battle}:{matchId:string;state:string;turn:string;ownSide:string;own:Pet[];rival:Pet[];battle:Battle}){const router=useRouter();const[pending,start]=useTransition();const act=(id:string)=>start(async()=>{const r=await submitArenaDraftAction(matchId,id,crypto.randomUUID());r.error?toast.error(r.error):toast.success(r.success);router.refresh()});const fight=()=>start(async()=>{const r=await resolveArenaDraftBattleAction(matchId);r.error?toast.error(r.error):toast.success(r.success);router.refresh()});const reveal=state==="TEAM_REVEAL";const banning=state==="BAN_PHASE";const picking=state==="PICK_PHASE";return <div className="space-y-5"><header className="rounded-3xl border border-fuchsia-400/25 bg-[radial-gradient(circle_at_top,rgba(168,85,247,.2),transparent_45%),#050916] p-6"><p className="text-[10px] font-black uppercase tracking-[.2em] text-fuchsia-300">Arena Draft · sala sincronizada</p><h1 className="mt-2 text-3xl font-black text-white">{reveal?"Inspeção das equipes":banning?"Fase de bans":picking?"Picks progressivos":state==="FINISHED"?"Partida finalizada":"Preparando combate"}</h1><p className="mt-2 text-sm text-slate-400">Estado {state} · {turn?`vez do lado ${turn}`:"aguarde o servidor"}</p>{reveal&&<button disabled={pending} onClick={()=>act("reveal")} className="mt-4 rounded-xl bg-cyan-300 px-5 py-3 text-xs font-black text-slate-950">Estou pronto para o draft</button>}</header><div className="grid gap-5 lg:grid-cols-2"><Team title="Sua equipe" pets={own} actionable={picking&&turn===ownSide} action="Escolher" onAction={act}/><Team title="Equipe adversária" pets={rival} actionable={banning&&turn===ownSide} action="Banir" onAction={act}/></div>{state==="BATTLE_INIT"&&<div className="rounded-2xl border border-amber-300/20 bg-amber-300/5 p-6 text-center"><b className="text-amber-200">Draft concluído</b><p className="mt-2 text-sm text-slate-400">As equipes estão congeladas. O servidor usará o motor oficial e salvará os eventos como replay, sem vídeo ou snapshots por turno.</p><button disabled={pending} onClick={fight} className="mt-4 rounded-xl bg-amber-300 px-5 py-3 text-xs font-black text-slate-950">Iniciar combate automático</button></div>}{state==="FINISHED"&&battle&&<Replay battle={battle}/>}</div>}
function Team({title,pets,actionable,action,onAction}:{title:string;pets:Pet[];actionable:boolean;action:string;onAction:(id:string)=>void}){return <section className="rounded-2xl border border-white/10 bg-slate-950/70 p-4"><h2 className="font-black text-white">{title}</h2><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{pets.map(p=><article key={p.id} className={`rounded-xl border p-3 text-center ${p.disabled?"border-rose-400/20 bg-rose-950/20 opacity-40":"border-white/10"}`}><img src={p.sprite} alt="" className="mx-auto h-16 w-16 object-contain"/><b className="block truncate text-xs text-white">{p.name}</b><p className="text-[9px] text-slate-500">{p.types.join(" · ")} {p.isMega&&"· MEGA"}</p>{actionable&&!p.disabled&&<button onClick={()=>onAction(p.id)} className="mt-2 w-full rounded-lg bg-fuchsia-500 px-2 py-2 text-[10px] font-bold text-white">{action}</button>}</article>)}</div></section>}
function Replay({battle}:{battle:NonNullable<Battle>}){return <section className="rounded-2xl border border-cyan-300/20 bg-slate-950/80 p-5"><div className="flex flex-wrap items-end justify-between gap-2"><div><p className="text-[10px] font-black uppercase tracking-widest text-cyan-300">Replay por eventos</p><h2 className="text-2xl font-black text-white">{battle.result==="ATTACKER_WIN"?"Vitória do lado A":battle.result==="DEFENDER_WIN"?"Vitória do lado B":"Empate"}</h2></div><p className="text-xs text-slate-400">{battle.rounds} ações registradas</p></div><div className="mt-4 max-h-[520px] space-y-2 overflow-y-auto pr-2">{battle.events?.map((event,index)=><div key={`${event.turn}-${index}`} className="rounded-xl border border-white/5 bg-white/[.025] p-3"><p className="text-[9px] font-bold uppercase text-slate-500">Evento {event.turn} · {event.action}</p><p className="text-xs text-slate-200"><b>{event.actorName}</b> → {event.targetName} · {event.damage} {event.action==="HEAL"?"HP":"dano"}</p>{event.effect&&<p className="mt-1 text-[10px] text-fuchsia-200">{event.effect}</p>}</div>)}</div></section>}
