ALTER TYPE "GachaObjectiveSource" ADD VALUE IF NOT EXISTS 'COMBATE_PVP';
ALTER TYPE "GachaObjectiveSource" ADD VALUE IF NOT EXISTS 'COMBATE_KO';
ALTER TYPE "GachaObjectiveSource" ADD VALUE IF NOT EXISTS 'LACOS';
ALTER TYPE "GachaObjectiveSource" ADD VALUE IF NOT EXISTS 'ALBUM_COMPLETO';
ALTER TYPE "GachaObjectiveSource" ADD VALUE IF NOT EXISTS 'LIGA_RUSH_VITORIA';
ALTER TYPE "GachaObjectiveSource" ADD VALUE IF NOT EXISTS 'LIGA_SEMANAL_VITORIA';
ALTER TYPE "GachaObjectiveSource" ADD VALUE IF NOT EXISTS 'BAZAR_COMPRA';
ALTER TYPE "GachaObjectiveSource" ADD VALUE IF NOT EXISTS 'MIAUVADAO_COMPRA_SLOT';
ALTER TYPE "GachaObjectiveSource" ADD VALUE IF NOT EXISTS 'MIAUVADAO_APOSTA';
ALTER TYPE "GachaObjectiveSource" ADD VALUE IF NOT EXISTS 'MIAUVADAO_ACERTO';
ALTER TYPE "GachaObjectiveSource" ADD VALUE IF NOT EXISTS 'ZIKABET_ACERTO';
ALTER TYPE "GachaObjectiveSource" ADD VALUE IF NOT EXISTS 'ZIKALOOT_NUMERO';
ALTER TYPE "GachaObjectiveSource" ADD VALUE IF NOT EXISTS 'ARENA_DRAFT_PARTIDA';
ALTER TYPE "GachaObjectiveSource" ADD VALUE IF NOT EXISTS 'EXPEDICAO_CONCLUIDA';

ALTER TABLE "gacha_missions"
  ADD COLUMN IF NOT EXISTS "criteria" JSONB;
