INSERT INTO "shop_items" ("id", "type", "name", "description", "rarity", "price", "active", "inventoryEnabled", "sortOrder", "metadata", "updatedAt") VALUES
('bond-shared-berry', 'BOND_SHARED_BERRY', 'Frutinha da Partilha', 'Em uma escolha positiva dos Laços, concede +4 de relação ao mascote principal e +2 ao outro mascote.', 'COMMON', 0, false, true, 900, '{"mode":"BONDS","effect":"relation","scoreDelta":4,"scoreDeltaB":2,"source":"GARDEN"}', NOW()),
('bond-calming-herb', 'BOND_CALMING_HERB', 'Erva Apaziguadora', 'Reduz em até 5 pontos a perda de relação causada por um conflito e registra uma memória de trégua. Não transforma Rival em Amigo.', 'UNCOMMON', 0, false, true, 901, '{"mode":"BONDS","effect":"preventNegative","maxPrevented":5,"source":"GARDEN"}', NOW()),
('bond-revenge-token', 'BOND_REVENGE_TOKEN', 'Ficha de Revanche', 'Transforma uma provocação em rivalidade controlada: aplica -4 de relação e impede que o mesmo evento cause uma perda maior.', 'COMMON', 0, false, true, 902, '{"mode":"BONDS","effect":"controlledRivalry","scoreDelta":-4,"source":"TRAINING"}', NOW()),
('bond-training-ribbon', 'BOND_TRAINING_RIBBON', 'Faixa de Treino em Dupla', 'Ao escolher cooperação no treino, concede +5 de relação e registra uma memória de parceria.', 'UNCOMMON', 0, false, true, 903, '{"mode":"BONDS","effect":"relation","scoreDelta":5,"source":"TRAINING"}', NOW()),
('bond-shared-pillow', 'BOND_SHARED_PILLOW', 'Almofada Compartilhada', 'Em um momento de descanso, concede +4 de relação e força a próxima memória da dupla a ser de cuidado ou ensino.', 'COMMON', 0, false, true, 904, '{"mode":"BONDS","effect":"relationAndCareMemory","scoreDelta":4,"source":"REST"}', NOW()),
('bond-night-tea', 'BOND_NIGHT_TEA', 'Chá de Boa-Noite', 'Remove a tensão do último conflito e concede +2 de relação nas duas direções entre os mascotes.', 'UNCOMMON', 0, false, true, 905, '{"mode":"BONDS","effect":"bidirectionalRelation","scoreDelta":2,"scoreDeltaB":2,"source":"REST"}', NOW()),
('bond-yard-toy', 'BOND_YARD_TOY', 'Brinquedo de Pátio', 'Faz o próximo acontecimento do Pátio tentar envolver 3 ou mais mascotes e favorece a formação de um círculo social.', 'COMMON', 0, false, true, 906, '{"mode":"BONDS","effect":"groupEvent","source":"YARD"}', NOW()),
('bond-illustrated-invitation', 'BOND_ILLUSTRATED_INVITATION', 'Convite Ilustrado', 'Permite escolher um mascote presente como alvo preferencial do próximo encontro. Não garante amizade nem rivalidade.', 'UNCOMMON', 0, false, true, 907, '{"mode":"BONDS","effect":"targetNextEncounter","source":"YARD"}', NOW()),
('bond-memory-album', 'BOND_MEMORY_ALBUM', 'Álbum de Memórias', 'Transforma uma memória comum em memória marcante e protegida. Não altera a pontuação da relação.', 'RARE', 0, false, true, 908, '{"mode":"BONDS","effect":"protectMemory"}', NOW()),
('bond-truce-bell', 'BOND_TRUCE_BELL', 'Sino de Trégua', 'Encerra um momento de conflito pendente e limita a mudança de relação daquele evento ao intervalo entre -2 e +2.', 'RARE', 0, false, true, 909, '{"mode":"BONDS","effect":"capEventDelta","min":-2,"max":2}', NOW()),
('bond-promise-charm', 'BOND_PROMISE_CHARM', 'Amuleto de Promessa', 'Protege um Laço Ativo contra adormecimento automático durante 30 dias. Não concede pontos de relação.', 'EPIC', 0, false, true, 910, '{"mode":"BONDS","effect":"protectBond","durationDays":30}', NOW()),
('bond-challenge-letter', 'BOND_CHALLENGE_LETTER', 'Carta de Desafio', 'Cria uma revanche direcionada entre dois mascotes que já sejam Rivais ou piores. Não cria rivalidade do zero.', 'RARE', 0, false, true, 911, '{"mode":"BONDS","effect":"targetRivalEvent","maxScore":-15}', NOW()),
('bond-taunt-whistle', 'BOND_TAUNT_WHISTLE', 'Apito de Provocação', 'No próximo encontro do Campo de Treino, aumenta a chance de conflito em 35 pontos percentuais. O conflito ainda respeita personalidade e histórico.', 'COMMON', 0, false, true, 912, '{"mode":"BONDS","effect":"conflictChance","bonusPct":35,"source":"TRAINING"}', NOW()),
('bond-challenge-board', 'BOND_CHALLENGE_BOARD', 'Quadro de Desafios', 'Escolhe um mascote como desafiante e procura um novo oponente compatível na mesma área, aumentando a chance de criar um novo Rival.', 'UNCOMMON', 0, false, true, 913, '{"mode":"BONDS","effect":"findNewRival","source":"TRAINING"}', NOW()),
('bond-second-place-medal', 'BOND_SECOND_PLACE_MEDAL', 'Medalha de Segundo Lugar', 'Após uma derrota em treino, aplica -5 de relação do perdedor para o vencedor e cria uma promessa de revanche.', 'UNCOMMON', 0, false, true, 914, '{"mode":"BONDS","effect":"loserRivalry","scoreDelta":-5,"source":"TRAINING"}', NOW()),
('bond-surpass-me-band', 'BOND_SURPASS_ME_BAND', 'Faixa “Me Supere”', 'Aplica -4 de relação nas duas direções e registra uma rivalidade saudável entre os dois mascotes escolhidos.', 'UNCOMMON', 0, false, true, 915, '{"mode":"BONDS","effect":"mutualRivalry","scoreDelta":-4,"scoreDeltaB":-4,"source":"TRAINING"}', NOW()),
('bond-cracked-trophy', 'BOND_CRACKED_TROPHY', 'Troféu Rachado', 'Converte uma relação de Conhecido em Rival, fixando a pontuação em -15. Só funciona entre mascotes que já interagiram.', 'RARE', 0, false, true, 916, '{"mode":"BONDS","effect":"setRival","targetScore":-15}', NOW()),
('bond-rival-circuit-pass', 'BOND_RIVAL_CIRCUIT_PASS', 'Passe do Circuito Rival', 'Gera uma sequência de até 3 desafios com o mesmo mascote contra oponentes diferentes, favorecendo a criação de novos Rivais. Cada desafio é resolvido separadamente.', 'EPIC', 0, false, true, 917, '{"mode":"BONDS","effect":"rivalCircuit","challenges":3}', NOW())
ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name", "description" = EXCLUDED."description", "rarity" = EXCLUDED."rarity",
  "active" = false, "inventoryEnabled" = true, "metadata" = EXCLUDED."metadata", "updatedAt" = NOW();
