"use client";

import { getStaticSpriteUrl } from "@/lib/mascot-data";

type Exploration = NonNullable<Extract<Awaited<ReturnType<typeof import("../actions").getTowerRunStateAction>>, { ok: true }>["exploration"]>;
const kindLabel: Record<string, string> = { ENTRANCE: "Entrada", PUZZLE: "Enigma", COMBAT: "Combate", REST: "Descanso", EVENT: "Evento", BOSS: "Líder", UNKNOWN: "Desconhecida" };
const positions: Record<string, [number, number]> = { entrance: [8, 50], puzzle: [30, 24], patrol: [30, 76], rest: [56, 18], gallery: [61, 62], boss: [88, 45] };
const edges: [string, string][] = [["entrance", "puzzle"], ["entrance", "patrol"], ["puzzle", "rest"], ["puzzle", "gallery"], ["patrol", "rest"], ["patrol", "gallery"], ["rest", "gallery"], ["gallery", "boss"]];

export function TowerRoomView({ exploration, routeId, puzzleChoice, roomAction, disabled, onRoute, onPuzzle, onRoomAction }: { exploration: Exploration; routeId?: string; puzzleChoice?: string; roomAction?: string; disabled: boolean; onRoute: (id: string) => void; onPuzzle: (id: string) => void; onRoomAction: (action: "INTERACT" | "SKIP") => void }) {
  const room = exploration.currentRoom;
  const visibleIds = new Set(exploration.rooms.filter((node) => node.visited || node.current || node.kind !== "UNKNOWN").map((node) => node.id));
  return <div className="space-y-4">
    <div className="relative min-h-[280px] overflow-hidden rounded-3xl border border-purple-400/35 bg-slate-950 shadow-[0_0_42px_rgba(126,34,206,.2)]">
      {/* eslint-disable-next-line @next/next/no-img-element */}<img src={room.backgroundUrl} alt="" className="absolute inset-0 h-full w-full object-cover opacity-45" />
      <div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/40 to-purple-950/30" />
      <div className="relative p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="rounded-full border border-purple-300/30 bg-purple-950/70 px-3 py-1 text-[10px] font-black uppercase tracking-widest text-purple-200">{kindLabel[room.kind] ?? room.kind}</span><h2 className="mt-3 text-2xl font-black text-white">{room.title}</h2><p className="mt-2 max-w-2xl text-sm text-slate-200">{room.description}</p></div><div className="rounded-2xl border border-red-400/30 bg-red-950/65 px-4 py-3 text-right"><p className="text-[9px] font-black uppercase tracking-widest text-red-300">Pressão</p><p className="text-2xl font-black text-red-200">{exploration.pressure}</p>{exploration.pressureShield > 0 && <p className="text-[9px] text-cyan-200">Proteção: {exploration.pressureShield}</p>}</div></div></div>
    </div>

    <div className="rounded-2xl border border-slate-700 bg-[#070b18] p-3 sm:p-5"><p className="text-[10px] font-black uppercase tracking-widest text-cyan-300">Mapa vivo do andar</p><p className="mb-3 text-[11px] text-slate-500">Linhas iluminadas são passagens conhecidas. Seu grupo é o marcador dourado.</p><div className="relative h-[320px] overflow-hidden rounded-xl border border-slate-800 bg-[radial-gradient(circle_at_center,rgba(88,28,135,.18),transparent_65%)]">
      <svg className="absolute inset-0 h-full w-full" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden>{edges.map(([a,b]) => { const [x1,y1]=positions[a], [x2,y2]=positions[b]; const known=visibleIds.has(a)&&visibleIds.has(b); return <line key={`${a}-${b}`} x1={x1} y1={y1} x2={x2} y2={y2} stroke={known?"#8b5cf6":"#263248"} strokeWidth={known?1.2:.55} strokeDasharray={known?"0":"2 2"}/>; })}</svg>
      {exploration.rooms.map((node) => { const [x,y]=positions[node.id]??[50,50]; const selectable=exploration.routes.some((route)=>route?.id===node.id); return <button type="button" key={node.id} disabled={disabled||!selectable} onClick={()=>selectable&&onRoute(node.id)} style={{left:`${x}%`,top:`${y}%`}} className={`absolute w-24 -translate-x-1/2 -translate-y-1/2 rounded-xl border px-2 py-2 text-center transition sm:w-32 ${node.current?"z-20 scale-110 border-[#FFCB05] bg-[#2a2104] text-[#FFCB05] shadow-[0_0_24px_rgba(255,203,5,.45)]":routeId===node.id?"border-cyan-300 bg-cyan-300/20 text-cyan-100":selectable?"border-purple-300 bg-purple-950/90 text-purple-100 hover:scale-105":node.visited?"border-purple-700 bg-slate-950/90 text-slate-300":"border-slate-700 bg-slate-950/85 text-slate-600"}`}><span className="block text-[9px] font-black uppercase">{node.current?"● Seu grupo":selectable?"→ Ir para":"○"}</span><b className="mt-1 block truncate text-[10px] sm:text-xs">{node.title}</b></button>; })}
    </div>{routeId && <p className="mt-3 rounded-lg bg-cyan-400/10 p-2 text-center text-xs font-bold text-cyan-200">Rota marcada. Confirme abaixo para percorrer esta passagem.</p>}</div>

    {exploration.modifiers.length > 0 && <div><p className="mb-2 text-[10px] font-black uppercase tracking-widest text-red-300">Por que a Torre está mais perigosa</p><div className="grid gap-2 sm:grid-cols-2">{exploration.modifiers.map((mod) => <div key={mod.key} className="rounded-xl border border-red-400/25 bg-red-950/20 p-3"><b className="text-sm text-red-200">⚠ {mod.name}</b><p className="mt-1 text-xs text-red-100/70">{mod.description}</p></div>)}</div><p className="mt-2 text-[11px] text-slate-500">A Pressão aumenta quando o grupo perde uma janela, erra mecanismos ou hesita. Percorrer uma rota válida não gera Pressão.</p></div>}

    {exploration.encounter && <div className="overflow-hidden rounded-2xl border border-red-400/40 bg-gradient-to-r from-red-950/50 to-purple-950/40"><div className="border-b border-red-300/15 p-4"><p className="text-[10px] font-black uppercase tracking-[.2em] text-red-300">⚔ Encontro hostil — preparação</p><h3 className="mt-1 text-lg font-black text-white">A passagem foi bloqueada</h3><p className="mt-1 text-xs text-slate-300">Será uma única batalha convencional com todos os aliados presentes contra todos os inimigos abaixo. Restam <b className="text-[#FFCB05]">{exploration.encounter.preparationTurns} janela(s)</b> para confirmar e permitir que aliados se preparem.</p></div><div className="grid gap-2 p-4 sm:grid-cols-2 lg:grid-cols-4">{exploration.encounter.enemies.map((enemy,index)=><div key={`${enemy.pokemonId}-${index}`} className="rounded-xl border border-red-300/20 bg-black/30 p-3 text-center">{/* eslint-disable-next-line @next/next/no-img-element */}<img src={getStaticSpriteUrl(enemy.pokemonId)} alt="" className="mx-auto h-16 w-16 object-contain [image-rendering:pixelated]"/><b className="mt-1 block text-sm text-red-100">{enemy.name}</b><span className="text-[10px] text-red-300">Nv.{enemy.level}</span></div>)}</div></div>}

    {!room.cleared && room.kind === "PUZZLE" && room.puzzle && <div className="rounded-2xl border border-amber-300/30 bg-amber-950/15 p-5"><p className="text-[10px] font-black uppercase tracking-widest text-amber-300">Enigma coletivo</p><h3 className="mt-2 font-bold text-white">{room.puzzle.prompt}</h3><p className="mt-1 text-xs text-slate-400">Escolha uma resposta ou deixe passar. A maioria das escolhas do grupo prevalece.</p>{room.puzzle.hint && <p className="mt-2 rounded-lg bg-cyan-400/10 p-2 text-xs text-cyan-200">📖 Pista: {room.puzzle.hint}</p>}<div className="mt-4 grid gap-2 sm:grid-cols-3">{room.puzzle.options.map((option) => <button type="button" disabled={disabled} key={option.id} onClick={() => onPuzzle(option.id)} className={`rounded-xl border p-3 text-sm font-bold ${puzzleChoice === option.id ? "border-amber-300 bg-amber-300/20 text-amber-100" : "border-slate-700 bg-slate-950/70 text-slate-300 hover:border-amber-300/50"}`}>{option.label}</button>)}</div></div>}

    {!room.cleared && room.kind === "REST" && !exploration.encounter && <div className="rounded-2xl border border-purple-400/25 bg-purple-950/15 p-4"><p className="text-sm text-purple-100">Uma chama desconhecida oferece descanso. O grupo decide conscientemente se interage ou segue adiante.</p><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" disabled={disabled} onClick={()=>onRoomAction("INTERACT")} className={`rounded-lg border py-2 text-xs font-black ${roomAction==="INTERACT"?"border-emerald-300 bg-emerald-300/15 text-emerald-200":"border-slate-700 text-slate-300"}`}>Investigar e usar</button><button type="button" disabled={disabled} onClick={()=>onRoomAction("SKIP")} className={`rounded-lg border py-2 text-xs font-black ${roomAction==="SKIP"?"border-amber-300 bg-amber-300/15 text-amber-200":"border-slate-700 text-slate-300"}`}>Ignorar e seguir</button></div></div>}
  </div>;
}
