"use client";
import { useEffect, useState } from "react";
const pages = [
  ["A Torre despertou", "Pikachu e sete regentes comandam mascotes que receberam uma consciência rebelde. Eles prometem libertá-los dos treinadores — mesmo que precisem transformar os demais em soldados da Torre."],
  ["Runs e caminhos", "Cada tentativa cria sete andares extensos com rotas, combates, enigmas, relíquias, portas e resgates. Cada ação aumenta a Pressão; votos por caminhos diferentes fazem a Torre reagir em dobro."],
  ["Cooperação", "No ritmo Online, as janelas duram 120 segundos e o legado obtido é maior. No ritmo Lento, quatro horas. Eventos e mecanismos são decididos pelos jogadores presentes na sala."],
  ["Classes e posturas", "Investigador revela pistas; Navegador reduz a primeira espera; Protetor reforça a equipe; Artífice contém mecanismos; Ritualista melhora curas; Batedor entra mais ágil. Classe e posturas ficam visíveis antes do Pronto."],
  ["Derrota, resgate e legado", "Mascotes derrotados — inclusive por remoção AFK — ficam sob controle da Torre. Sem mascotes, você permanece como espectador e não bloqueia o grupo. Pontos de talento são comunitários."],
  ["Objetivo", "Derrote os sete chefes, reúna informações no Arquivo comunitário e interrompa o plano de Pikachu. Cada descoberta torna as tentativas seguintes mais inteligentes."],
] as const;
export function TowerIntro({ forceKey = 0 }: { forceKey?: number }) {
 const [open,setOpen]=useState(false);const [page,setPage]=useState(0);
 useEffect(()=>{if(forceKey>0){setPage(0);setOpen(true);return}if(!localStorage.getItem("tower-intro-seen-v3"))setOpen(true)},[forceKey]);
 if(!open)return null;const close=()=>{localStorage.setItem("tower-intro-seen-v3","1");setOpen(false)};
 return <div className="fixed inset-0 z-[80] flex items-center justify-center overflow-y-auto bg-black/90 p-3"><div className="my-auto w-full max-w-4xl overflow-hidden rounded-3xl border border-purple-400/40 bg-slate-950 shadow-[0_0_70px_rgba(126,34,206,.4)]"><div className="relative h-72 overflow-hidden sm:h-96">{/* eslint-disable-next-line @next/next/no-img-element */}<img src="/events/torre-dos-rebeldes/cover.png" alt="Torre dos Rebeldes" className="h-full w-full scale-[1.22] object-cover object-[center_38%]"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-transparent to-black/10"/><button onClick={close} className="absolute right-3 top-3 rounded-full bg-black/70 px-3 py-2 text-white">✕</button></div><div className="p-5 sm:p-7"><p className="text-[10px] font-black uppercase tracking-[.25em] text-purple-300">Guia da expedição · {page+1}/{pages.length}</p><h2 className="mt-2 text-2xl font-black text-white">{pages[page][0]}</h2><p className="mt-3 min-h-20 text-sm leading-relaxed text-slate-300">{pages[page][1]}</p><div className="mt-5 flex items-center justify-between"><button disabled={page===0} onClick={()=>setPage(value=>value-1)} className="rounded-xl border border-slate-700 px-4 py-2 text-sm text-slate-300 disabled:opacity-30">Anterior</button><div className="flex gap-1">{pages.map((_,index)=><span key={index} className={`h-2 rounded-full ${index===page?"w-6 bg-[#FFCB05]":"w-2 bg-slate-700"}`}/>)}</div>{page<pages.length-1?<button onClick={()=>setPage(value=>value+1)} className="rounded-xl bg-[#FFCB05] px-4 py-2 text-sm font-black text-slate-950">Próxima</button>:<button onClick={close} className="rounded-xl bg-emerald-400 px-4 py-2 text-sm font-black text-emerald-950">Entrar na Torre</button>}</div></div></div></div>;
}
