"use client";
import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
type Unit={id:string;name:string;pokemonId:number;hp:number;maxHp:number;team:string;role:string};
type Event={unitId:string;targetId?:string;kind:string;text:string;amount?:number};
const sprite=(id:number)=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/${id}.gif`;
export function TowerCombatScene({events,units,turn}:{events:Event[];units:Unit[];turn:number|null}){
 const relevant=useMemo(()=>events.filter(e=>e.kind!=="MOVE"),[events]);
 const [index,setIndex]=useState(0),[open,setOpen]=useState(false);
 useEffect(()=>{if(!relevant.length)return;setIndex(0);setOpen(true)},[turn,relevant.length]);
 useEffect(()=>{if(!open||index>=relevant.length-1)return;const timer=setTimeout(()=>setIndex(i=>i+1),1800);return()=>clearTimeout(timer)},[open,index,relevant.length]);
 if(!open||!relevant.length)return null;const event=relevant[index],actor=units.find(u=>u.id===event.unitId),target=units.find(u=>u.id===event.targetId);
 return <div className="fixed inset-0 z-[90] grid place-items-center bg-black/75 p-4 backdrop-blur-sm"><section className="relative w-full max-w-3xl overflow-hidden rounded-3xl border border-purple-300/40 bg-[#090512] p-5 shadow-[0_0_80px_rgba(126,34,206,.45)]"><button onClick={()=>setOpen(false)} className="absolute right-4 top-4 z-10 rounded-lg bg-black/50 px-3 py-1 text-xs text-slate-300">Pular</button><p className="text-center text-[10px] font-black uppercase tracking-[.28em] text-purple-300">Confronto · turno {turn}</p><div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-4"><Fighter unit={actor} side="ATACANTE"/><div className="text-center"><div className={`mx-auto grid h-16 w-16 place-items-center rounded-full text-xl font-black ${event.kind==="KO"?"animate-pulse bg-red-500 text-white":"bg-purple-500/20 text-purple-100"}`}>{event.kind==="KO"?"K.O.":event.amount?`-${event.amount}`:"✦"}</div><p className="mt-3 max-w-52 text-xs leading-relaxed text-slate-200">{event.text}</p></div><Fighter unit={target} side="DEFENSOR"/></div><div className="mt-5 h-1 overflow-hidden rounded bg-slate-800"><span className="block h-full bg-purple-400 transition-all duration-500" style={{width:`${((index+1)/relevant.length)*100}%`}}/></div></section></div>
}
function Fighter({unit,side}:{unit?:Unit;side:string}){if(!unit)return <div className="text-center text-slate-600">Efeito da Torre</div>;const custom=unit.pokemonId>=210001&&unit.pokemonId<=210008;return <div className={`rounded-2xl border p-4 text-center ${unit.team==="ALLY"?"border-cyan-400/35 bg-cyan-950/25":"border-red-400/35 bg-red-950/25"}`}><small className="font-black tracking-widest text-slate-400">{side}</small><Image unoptimized src={sprite(unit.pokemonId)} alt={unit.name} width={150} height={150} className={`mx-auto h-36 w-36 object-contain ${custom?"":"[image-rendering:pixelated]"}`}/><b className="block text-white">{unit.name}</b><span className="text-[10px] text-purple-200">{unit.role}</span><div className="mt-2 h-2 overflow-hidden rounded bg-black"><i className="block h-full bg-emerald-400" style={{width:`${Math.max(0,unit.hp/unit.maxHp*100)}%`}}/></div><small className="mt-1 block text-slate-400">{unit.hp}/{unit.maxHp} HP</small></div>}
