"use client";
import { useState,useTransition } from "react";
import { toast } from "sonner";
import type { TowerConfig } from "@/lib/tower/config";
import { adminResetTowerEventAction,clearMyTowerCooldownAction,debugGrantTowerBossChoiceAction,debugTowerMascotRewardPreviewAction,saveTowerConfigAction } from "../actions";
import { TOWER_EXCLUSIVE_MASCOTS } from "@/lib/tower/exclusive-catalog";

type DebugPreview = { pokemonId:number; name:string; code:string; sprite:string; level:number; origin:string; alreadyClaimed:boolean; pending:boolean; stats:{statForce:number;statAgility:number;statCharisma:number;statInstinct:number;statVitality:number} };
const DEBUG_PERSONALITIES = [["LOYAL","Leal"],["PROUD","Orgulhoso"],["MISCHIEVOUS","Travesso"],["LAZY","Preguiçoso"],["COMPETITIVE","Competitivo"],["DRAMATIC","Dramático"],["PLAYFUL","Brincalhão"],["ELECTRIC","Elétrico"],["TIMID","Tímido"],["CHAOTIC","Caótico"],["CURIOUS","Curioso"],["GLUTTON","Guloso"],["SERENE","Sereno"]] as const;

export function TowerAdminSettings({initial,onSaved}:{initial:TowerConfig;onSaved?:()=>void}){
 const [config,setConfig]=useState(initial),[open,setOpen]=useState(false),[pending,start]=useTransition();
 const [debugPersonality,setDebugPersonality]=useState("LOYAL"),[debugPreview,setDebugPreview]=useState<DebugPreview|null>(null);
 const clear=()=>start(async()=>{const r=await clearMyTowerCooldownAction();if("error"in r)toast.error(r.error);else{toast.success("Seu cooldown atual foi removido.");onSaved?.()}});
 const save=()=>start(async()=>{const r=await saveTowerConfigAction(config);if("error"in r)toast.error(r.error);else{setConfig(r.config);toast.success("Configuração da Torre atualizada.");onSaved?.()}});
 const reset=()=>{if(!confirm("Apagar runs, resgates, ranking, descobertas e talentos da Torre?"))return;start(async()=>{const r=await adminResetTowerEventAction("RESETAR TORRE");if("error"in r)toast.error(r.error);else{toast.success("Evento completamente resetado.");onSaved?.()}})};
 const simulate=(pokemonId:number)=>start(async()=>{const r=await debugTowerMascotRewardPreviewAction(pokemonId,debugPersonality as never);if("error"in r)toast.error(r.error);else setDebugPreview(r.mascot)});
 return <>
  <section className="rounded-2xl border border-amber-400/25 bg-amber-950/10 p-4">
   <button onClick={()=>setOpen(v=>!v)} className="flex w-full items-center justify-between text-left"><span><b className="text-white">⚙ Administração da Torre</b><small className="mt-1 block text-slate-400">Cooldown, tickets, mascotes exclusivos e reinicialização.</small></span><span className="text-amber-300">{open?"Fechar":"Configurar"}</span></button>
   {open&&<div className="mt-4 grid gap-3 md:grid-cols-2">
    <label className="rounded-xl border border-slate-700 bg-black/20 p-3 text-xs text-slate-300">Cooldown global em minutos<input type="number" min={0} max={10080} value={config.entryCooldownMinutes} onChange={e=>setConfig(c=>({...c,entryCooldownMinutes:Number(e.target.value)}))} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 p-2 text-white"/></label>
    <label className="flex items-center gap-3 rounded-xl border border-slate-700 bg-black/20 p-3 text-xs text-slate-300"><input type="checkbox" checked={config.requireTicket} onChange={e=>setConfig(c=>({...c,requireTicket:e.target.checked}))}/><span><b className="block text-white">Exigir Ticket da Torre</b>É consumido somente quando o host inicia a partida.</span></label>
    <button disabled={pending} onClick={save} className="rounded-xl bg-amber-400 py-2.5 text-xs font-black text-amber-950 disabled:opacity-50">Salvar configuração</button>
    <button disabled={pending} onClick={clear} className="rounded-xl border border-cyan-400/40 bg-cyan-400/10 py-2.5 text-xs font-black text-cyan-200 disabled:opacity-50">Liberar minha entrada</button>
    <div className="rounded-xl border border-fuchsia-400/25 bg-fuchsia-950/15 p-3 md:col-span-2">
     <div className="flex flex-wrap items-end justify-between gap-2"><span><b className="text-xs text-fuchsia-200">Debug da janela de criação</b><small className="mt-1 block text-[10px] text-slate-400">Simula na conta admin sem entregar mascote nem alterar a derrota do chefe.</small></span><select value={debugPersonality} onChange={e=>setDebugPersonality(e.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 p-2 text-xs text-white">{DEBUG_PERSONALITIES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
     <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{TOWER_EXCLUSIVE_MASCOTS.map(mascot=><button key={mascot.code} disabled={pending} onClick={()=>simulate(mascot.pokemonId)} className="flex items-center gap-2 rounded-xl border border-fuchsia-300/20 bg-black/25 p-2 text-left hover:border-fuchsia-300/60 disabled:opacity-40"><img src={mascot.sprite} alt="" className="h-12 w-12 object-contain"/><span className="min-w-0"><b className="block truncate text-[11px] text-white">{mascot.name}</b><code className="text-[9px] text-fuchsia-300">ID {mascot.pokemonId}</code></span></button>)}</div>
    </div>
    <div className="rounded-xl border border-purple-400/25 bg-purple-950/15 p-3 md:col-span-2"><b className="text-xs text-purple-200">Cola para envio manual</b><div className="mt-2 grid gap-1 sm:grid-cols-2">{TOWER_EXCLUSIVE_MASCOTS.map(mascot=><code key={mascot.code} className="rounded bg-black/30 p-2 text-[10px] text-slate-300">{mascot.code} · ID {mascot.pokemonId} · {mascot.name}</code>)}</div></div>
    <button disabled={pending} onClick={()=>start(async()=>{const result=await debugGrantTowerBossChoiceAction();if("error" in result)toast.error(result.error);else{toast.success("Janela de escolha final liberada para teste.");onSaved?.()}})} className="rounded-xl border border-amber-300/40 bg-amber-300/10 py-2.5 text-xs font-black text-amber-200 disabled:opacity-50 md:col-span-2">🧪 Testar escolha única após o último andar</button>
    <button disabled={pending} onClick={reset} className="rounded-xl border border-red-400/40 bg-red-400/10 py-2.5 text-xs font-black text-red-200 disabled:opacity-50 md:col-span-2">Resetar evento inteiro</button>
   </div>}
  </section>
  {debugPreview&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/85 p-4" onMouseDown={()=>setDebugPreview(null)}><section onMouseDown={e=>e.stopPropagation()} className="w-full max-w-xl overflow-hidden rounded-3xl border border-fuchsia-300/40 bg-slate-950 shadow-[0_0_70px_rgba(217,70,239,.25)]"><div className="relative bg-gradient-to-br from-purple-950 via-slate-950 to-fuchsia-950 p-6 text-center"><button onClick={()=>setDebugPreview(null)} className="absolute right-3 top-3 rounded-full bg-black/50 px-3 py-2 text-white">✕</button><p className="text-[10px] font-black uppercase tracking-[.25em] text-fuchsia-300">Simulação administrativa · nada será entregue</p><img src={debugPreview.sprite} alt={debugPreview.name} className="mx-auto mt-4 h-44 w-44 object-contain drop-shadow-[0_0_22px_rgba(232,121,249,.45)]"/><h2 className="text-2xl font-black text-white">{debugPreview.name}</h2><p className="mt-1 text-xs text-fuchsia-200">Nv.{debugPreview.level} · {debugPreview.origin}</p></div><div className="p-5"><div className="grid grid-cols-5 gap-2 text-center">{[["FOR",debugPreview.stats.statForce],["AGI",debugPreview.stats.statAgility],["CAR",debugPreview.stats.statCharisma],["INS",debugPreview.stats.statInstinct],["VIT",debugPreview.stats.statVitality]].map(([label,value])=><div key={label} className="rounded-xl border border-slate-800 bg-slate-900 p-2"><small className="block text-[9px] text-slate-500">{label}</small><b className="text-sm text-white">{value}</b></div>)}</div><div className="mt-4 rounded-xl border border-slate-800 bg-black/25 p-3 text-xs text-slate-300"><b className="text-white">Estado real na conta admin</b><p className="mt-1">{debugPreview.alreadyClaimed?"✓ Já recebido. Novas vitórias não entregarão outra cópia.":debugPreview.pending?"Aguardando a escolha de personalidade na janela real.":"Ainda não recebido. O chefe libera a recompensa uma única vez; Xandinho é liberado após a primeira run perdida."}</p></div><button disabled={pending} onClick={()=>simulate(debugPreview.pokemonId)} className="mt-4 w-full rounded-xl bg-fuchsia-400 py-2 text-xs font-black text-fuchsia-950 disabled:opacity-40">Gerar outra simulação com {DEBUG_PERSONALITIES.find(([value])=>value===debugPersonality)?.[1]}</button></div></section></div>}
 </>;
}
