"use client";
import { useState,useTransition } from "react";
import { toast } from "sonner";
import type { TowerConfig } from "@/lib/tower/config";
import type { TowerNarrativeScene } from "@/lib/tower/narrative";
import { TOWER_COMMUNITY_STUDIES, type TowerStudyKey } from "@/lib/tower/studies";
import { adminAddTowerTesterAction,adminControlTowerNarrativeAction,adminControlTowerRunAction,adminControlTowerStudyAction,adminRemoveTowerTesterAction,adminResetTowerEventAction,clearMyTowerCooldownAction,debugGrantTowerBossChoiceAction,debugTowerMascotRewardPreviewAction,saveTowerConfigAction } from "../actions";
import { TOWER_EXCLUSIVE_MASCOTS } from "@/lib/tower/exclusive-catalog";

type DebugPreview = { pokemonId:number; name:string; code:string; sprite:string; level:number; origin:string; alreadyClaimed:boolean; pending:boolean; stats:{statForce:number;statAgility:number;statCharisma:number;statInstinct:number;statVitality:number} };
const DEBUG_PERSONALITIES = [["LOYAL","Leal"],["PROUD","Orgulhoso"],["MISCHIEVOUS","Travesso"],["LAZY","Preguiçoso"],["COMPETITIVE","Competitivo"],["DRAMATIC","Dramático"],["PLAYFUL","Brincalhão"],["ELECTRIC","Elétrico"],["TIMID","Tímido"],["CHAOTIC","Caótico"],["CURIOUS","Curioso"],["GLUTTON","Guloso"],["SERENE","Sereno"]] as const;

export function TowerAdminSettings({initial,onSaved,activeRunId,scenes=[],highestReachedFloor=1,communityProgress=[],allowedPlayers=[]}:{initial:TowerConfig;onSaved?:()=>void;activeRunId?:string;scenes?:TowerNarrativeScene[];highestReachedFloor?:number;communityProgress?:Array<{metricKey:string;value:number}>;allowedPlayers?:Array<{userId:string;name:string;email:string}>}){
 const [config,setConfig]=useState(initial),[open,setOpen]=useState(false),[pending,start]=useTransition();
 const [debugPersonality,setDebugPersonality]=useState("LOYAL"),[debugPreview,setDebugPreview]=useState<DebugPreview|null>(null);
 const [studyKey,setStudyKey]=useState<TowerStudyKey>("WARD"),[narrativeTarget,setNarrativeTarget]=useState(scenes[0]?.id??"");
 const [testerQuery,setTesterQuery]=useState("");
 const clear=()=>start(async()=>{const r=await clearMyTowerCooldownAction();if("error"in r)toast.error(r.error);else{toast.success("Seu cooldown atual foi removido.");onSaved?.()}});
 const save=()=>start(async()=>{const r=await saveTowerConfigAction(config);if("error"in r)toast.error(r.error);else{setConfig(r.config);toast.success("Configuração da Torre atualizada.");onSaved?.()}});
 const reset=()=>{if(!confirm("Apagar runs, resgates, ranking, descobertas e talentos da Torre?"))return;start(async()=>{const r=await adminResetTowerEventAction("RESETAR TORRE");if("error"in r)toast.error(r.error);else{toast.success("Evento completamente resetado.");onSaved?.()}})};
 const simulate=(pokemonId:number)=>start(async()=>{const r=await debugTowerMascotRewardPreviewAction(pokemonId,debugPersonality as never);if("error"in r)toast.error(r.error);else setDebugPreview(r.mascot)});
 const runControl=(operation:Parameters<typeof adminControlTowerRunAction>[1])=>{if(!activeRunId)return;start(async()=>{const r=await adminControlTowerRunAction(activeRunId,operation);if("error"in r)toast.error(r.error);else{toast.success(`Run atualizada · Pressão ${r.pressure} · Proteção ${r.pressureShield}`);onSaved?.()}})};
 const studyControl=(operation:"INCREMENT"|"COMPLETE"|"RESET",key:TowerStudyKey|"ALL"=studyKey)=>start(async()=>{const r=await adminControlTowerStudyAction(key,operation);if("error"in r)toast.error(r.error);else{toast.success("Reforços comunitários atualizados.");onSaved?.()}});
 const narrativeControl=(operation:"UNLOCK_SCENE"|"UNLOCK_GROUP"|"UNLOCK_FLOOR"|"UNLOCK_ALL"|"RESET",value?:string)=>start(async()=>{const r=await adminControlTowerNarrativeAction(operation,value);if("error"in r)toast.error(r.error);else{toast.success(operation==="RESET"?"Desbloqueios narrativos reiniciados.":`${r.count} diálogo(s) liberado(s).`);onSaved?.()}});
 return <>
  <section className="rounded-2xl border border-amber-400/25 bg-amber-950/10 p-4">
   <button onClick={()=>setOpen(v=>!v)} className="flex w-full items-center justify-between text-left"><span><b className="text-white">⚙ Administração da Torre</b><small className="mt-1 block text-slate-400">Cooldown, tickets, mascotes exclusivos e reinicialização.</small></span><span className="text-amber-300">{open?"Fechar":"Configurar"}</span></button>
   {open&&<div className="mt-4 grid gap-3 md:grid-cols-2">
    <label className="rounded-xl border border-slate-700 bg-black/20 p-3 text-xs text-slate-300">Cooldown global em minutos<input type="number" min={0} max={10080} value={config.entryCooldownMinutes} onChange={e=>setConfig(c=>({...c,entryCooldownMinutes:Number(e.target.value)}))} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 p-2 text-white"/></label>
    <label className="flex items-center gap-3 rounded-xl border border-slate-700 bg-black/20 p-3 text-xs text-slate-300"><input type="checkbox" checked={config.requireTicket} onChange={e=>setConfig(c=>({...c,requireTicket:e.target.checked}))}/><span><b className="block text-white">Exigir Ticket da Torre</b>É consumido somente quando o host inicia a partida.</span></label>
    <button disabled={pending} onClick={save} className="rounded-xl bg-amber-400 py-2.5 text-xs font-black text-amber-950 disabled:opacity-50">Salvar configuração</button>
    <button disabled={pending} onClick={clear} className="rounded-xl border border-cyan-400/40 bg-cyan-400/10 py-2.5 text-xs font-black text-cyan-200 disabled:opacity-50">Liberar minha entrada</button>
    <div className="rounded-xl border border-cyan-400/25 bg-cyan-950/15 p-3 md:col-span-2">
     <b className="text-xs text-cyan-200">Acesso fechado para testes multiplayer</b><small className="mt-1 block text-slate-400">Procure pelo nome ou e-mail. A conta liberada joga normalmente, mas não recebe acesso às ferramentas administrativas.</small>
     <div className="mt-3 flex gap-2"><input value={testerQuery} onChange={e=>setTesterQuery(e.target.value)} placeholder="Nome do jogador ou e-mail" className="min-w-0 flex-1 rounded-lg border border-slate-700 bg-slate-950 p-2 text-xs text-white"/><button disabled={pending||testerQuery.trim().length<2} onClick={()=>start(async()=>{const r=await adminAddTowerTesterAction(testerQuery);if("error"in r)toast.error(r.error);else{toast.success(`${r.player.name} recebeu acesso à Torre.`);setTesterQuery("");onSaved?.()}})} className="rounded-lg border border-cyan-400/30 px-3 text-xs font-black text-cyan-200 disabled:opacity-40">Adicionar</button></div>
     <div className="mt-3 grid gap-2 sm:grid-cols-2">{allowedPlayers.length===0?<p className="text-[10px] text-slate-500">Nenhuma conta comum liberada ainda.</p>:allowedPlayers.map(player=><div key={player.userId} className="flex items-center justify-between gap-2 rounded-lg border border-slate-800 bg-black/25 p-2"><span className="min-w-0 text-[10px]"><b className="block truncate text-white">{player.name}</b><small className="block truncate text-slate-500">{player.email}</small></span><button disabled={pending} onClick={()=>start(async()=>{const r=await adminRemoveTowerTesterAction(player.userId);if("error"in r)toast.error(r.error);else{toast.success("Acesso removido.");onSaved?.()}})} className="rounded border border-red-400/30 px-2 py-1 text-[9px] font-black text-red-300">Remover</button></div>)}</div>
    </div>
    <div className="rounded-xl border border-red-400/25 bg-red-950/15 p-3 md:col-span-2">
     <b className="text-xs text-red-200">Console da run ativa</b><small className="mt-1 block text-slate-400">Pressão recalcula os modificadores imediatamente. “Resetar buffs” remove contramedidas e escudos da run sem apagar seu progresso.</small>
     <div className="mt-3 grid gap-2 sm:grid-cols-3 lg:grid-cols-6"><button disabled={pending||!activeRunId} onClick={()=>runControl("PRESSURE_REMOVE")} className="rounded-lg border border-slate-700 p-2 text-xs">− Pressão</button><button disabled={pending||!activeRunId} onClick={()=>runControl("PRESSURE_ADD")} className="rounded-lg border border-red-400/30 p-2 text-xs text-red-200">+ Pressão</button><button disabled={pending||!activeRunId} onClick={()=>runControl("PRESSURE_RESET")} className="rounded-lg border border-slate-700 p-2 text-xs">Zerar pressão</button><button disabled={pending||!activeRunId} onClick={()=>runControl("SHIELD_ADD")} className="rounded-lg border border-cyan-400/30 p-2 text-xs text-cyan-200">+ Proteção</button><button disabled={pending||!activeRunId} onClick={()=>runControl("BUFFS_RESET")} className="rounded-lg border border-amber-400/30 p-2 text-xs text-amber-200 sm:col-span-2">Resetar buffs/contramedidas</button></div>
    </div>
    <div className="rounded-xl border border-emerald-400/25 bg-emerald-950/15 p-3 md:col-span-2">
     <b className="text-xs text-emerald-200">Estudos e buffs da comunidade</b><div className="mt-2 flex flex-wrap gap-2"><select value={studyKey} onChange={e=>setStudyKey(e.target.value as TowerStudyKey)} className="min-w-56 flex-1 rounded-lg border border-slate-700 bg-slate-950 p-2 text-xs text-white">{TOWER_COMMUNITY_STUDIES.map(study=><option key={study.key} value={study.key}>{study.title} · {communityProgress.find(row=>row.metricKey===study.key)?.value??0}/25</option>)}</select><button disabled={pending} onClick={()=>studyControl("INCREMENT")} className="rounded-lg border border-emerald-400/30 px-3 text-xs text-emerald-200">+1</button><button disabled={pending} onClick={()=>studyControl("COMPLETE")} className="rounded-lg border border-emerald-400/30 px-3 text-xs text-emerald-200">Completar 25/25</button><button disabled={pending} onClick={()=>studyControl("RESET")} className="rounded-lg border border-slate-700 px-3 text-xs">Resetar este</button><button disabled={pending} onClick={()=>studyControl("RESET","ALL")} className="rounded-lg border border-red-400/30 px-3 text-xs text-red-200">Resetar todos</button></div>
    </div>
    <div className="rounded-xl border border-purple-400/25 bg-purple-950/15 p-3 md:col-span-2">
     <div className="flex flex-wrap items-center justify-between gap-2"><span><b className="text-xs text-purple-200">Progressão narrativa e andares</b><small className="mt-1 block text-slate-400">Andar visível atual: {highestReachedFloor}/7. Conteúdo futuro aparece como “???”.</small></span><div className="flex gap-1">{[1,2,3,4,5,6,7].map(floor=><button key={floor} disabled={pending} onClick={()=>narrativeControl("UNLOCK_FLOOR",String(floor))} className={`h-8 w-8 rounded-lg border text-xs font-black ${floor<=highestReachedFloor?"border-purple-300 bg-purple-300/15 text-purple-100":"border-slate-700 text-slate-500"}`}>{floor}</button>)}</div></div>
     <div className="mt-3 flex flex-wrap gap-2"><select value={narrativeTarget} onChange={e=>setNarrativeTarget(e.target.value)} className="min-w-64 flex-1 rounded-lg border border-slate-700 bg-slate-950 p-2 text-xs text-white">{scenes.map(scene=><option key={scene.id} value={scene.id}>Andar {scene.floor||"geral"} · {scene.groupTitle} · {scene.title}</option>)}</select><button disabled={pending||!narrativeTarget} onClick={()=>narrativeControl("UNLOCK_SCENE",narrativeTarget)} className="rounded-lg border border-purple-400/30 px-3 text-xs text-purple-200">Liberar diálogo</button><button disabled={pending} onClick={()=>narrativeControl("UNLOCK_ALL")} className="rounded-lg border border-amber-400/30 px-3 text-xs text-amber-200">Liberar tudo</button><button disabled={pending} onClick={()=>narrativeControl("RESET")} className="rounded-lg border border-red-400/30 px-3 text-xs text-red-200">Resetar desbloqueios narrativos</button></div>
    </div>
    <div className="rounded-xl border border-fuchsia-400/25 bg-fuchsia-950/15 p-3 md:col-span-2">
     <div className="flex flex-wrap items-end justify-between gap-2"><span><b className="text-xs text-fuchsia-200">Debug da janela de criação</b><small className="mt-1 block text-[10px] text-slate-400">Simula na conta admin sem entregar mascote nem alterar a derrota do chefe.</small></span><select value={debugPersonality} onChange={e=>setDebugPersonality(e.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 p-2 text-xs text-white">{DEBUG_PERSONALITIES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
     <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{TOWER_EXCLUSIVE_MASCOTS.map(mascot=><button key={mascot.code} disabled={pending} onClick={()=>simulate(mascot.pokemonId)} className="flex items-center gap-2 rounded-xl border border-fuchsia-300/20 bg-black/25 p-2 text-left hover:border-fuchsia-300/60 disabled:opacity-40"><img src={mascot.sprite} alt="" className="h-12 w-12 object-contain"/><span className="min-w-0"><b className="block truncate text-[11px] text-white">{mascot.name}</b><code className="text-[9px] text-fuchsia-300">ID {mascot.pokemonId}</code></span></button>)}</div>
    </div>
    <div className="rounded-xl border border-purple-400/25 bg-purple-950/15 p-3 md:col-span-2"><b className="text-xs text-purple-200">Cola para envio manual</b><div className="mt-2 grid gap-1 sm:grid-cols-2">{TOWER_EXCLUSIVE_MASCOTS.map(mascot=><code key={mascot.code} className="rounded bg-black/30 p-2 text-[10px] text-slate-300">{mascot.code} · ID {mascot.pokemonId} · {mascot.name}</code>)}</div></div>
    <button disabled={pending} onClick={()=>start(async()=>{const result=await debugGrantTowerBossChoiceAction();if("error" in result)toast.error(result.error);else{toast.success("Janela de escolha final liberada para teste.");onSaved?.()}})} className="rounded-xl border border-amber-300/40 bg-amber-300/10 py-2.5 text-xs font-black text-amber-200 disabled:opacity-50 md:col-span-2">🧪 Testar escolha única após o último andar</button>
    <button disabled={pending} onClick={reset} className="rounded-xl border border-red-400/40 bg-red-400/10 py-2.5 text-xs font-black text-red-200 disabled:opacity-50 md:col-span-2">Resetar evento inteiro</button>
   </div>}
  </section>
  {debugPreview&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/85 p-4" onMouseDown={()=>setDebugPreview(null)}><section onMouseDown={e=>e.stopPropagation()} className="w-full max-w-xl overflow-hidden rounded-3xl border border-fuchsia-300/40 bg-slate-950 shadow-[0_0_70px_rgba(217,70,239,.25)]"><div className="relative bg-gradient-to-br from-purple-950 via-slate-950 to-fuchsia-950 p-6 text-center"><button onClick={()=>setDebugPreview(null)} className="absolute right-3 top-3 rounded-full bg-black/50 px-3 py-2 text-white">✕</button><p className="text-[10px] font-black uppercase tracking-[.25em] text-fuchsia-300">Simulação administrativa · nada será entregue</p><img src={debugPreview.sprite} alt={debugPreview.name} className="mx-auto mt-4 h-44 w-44 object-contain drop-shadow-[0_0_22px_rgba(232,121,249,.45)]"/><h2 className="text-2xl font-black text-white">{debugPreview.name}</h2><p className="mt-1 text-xs text-fuchsia-200">Nv.{debugPreview.level} · {debugPreview.origin}</p></div><div className="p-5"><div className="grid grid-cols-5 gap-2 text-center">{[["FOR",debugPreview.stats.statForce],["AGI",debugPreview.stats.statAgility],["CAR",debugPreview.stats.statCharisma],["INS",debugPreview.stats.statInstinct],["VIT",debugPreview.stats.statVitality]].map(([label,value])=><div key={label} className="rounded-xl border border-slate-800 bg-slate-900 p-2"><small className="block text-[9px] text-slate-500">{label}</small><b className="text-sm text-white">{value}</b></div>)}</div><div className="mt-4 rounded-xl border border-slate-800 bg-black/25 p-3 text-xs text-slate-300"><b className="text-white">Estado real na conta admin</b><p className="mt-1">{debugPreview.alreadyClaimed?"✓ Já recebido. Novas vitórias não entregarão outra cópia.":debugPreview.pending?"Aguardando a escolha de personalidade na janela real.":"Ainda não recebido. O chefe libera a recompensa uma única vez; Xandinho é liberado após a primeira run perdida."}</p></div><button disabled={pending} onClick={()=>simulate(debugPreview.pokemonId)} className="mt-4 w-full rounded-xl bg-fuchsia-400 py-2 text-xs font-black text-fuchsia-950 disabled:opacity-40">Gerar outra simulação com {DEBUG_PERSONALITIES.find(([value])=>value===debugPersonality)?.[1]}</button></div></section></div>}
 </>;
}
