ALTER TABLE "players"
ADD COLUMN IF NOT EXISTS "deliveryHomeLabel" TEXT,
ADD COLUMN IF NOT EXISTS "deliveryHomeLatitude" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "deliveryHomeLongitude" DOUBLE PRECISION;
