"use client";

import { useEffect, useState, useTransition } from "react";
import { Dna, Search, Sparkles, UserRoundSearch } from "lucide-react";
import { PlayerSearchInput } from "@/components/player-search-input";
import { createCustomSpeciesAdminAction, getPlayerMascotEditorData, searchSpeciesAdminAction, updateMascotAdminAction, updateSpeciesTypesAdminAction } from "./actions";

type Mascot = Awaited<ReturnType<typeof getPlayerMascotEditorData>>[number];
type Species = Awaited<ReturnType<typeof searchSpeciesAdminAction>>[number];
const PERSONALITIES = ["LOYAL","PROUD","MISCHIEVOUS","LAZY","COMPETITIVE","DRAMATIC","PLAYFUL","ELECTRIC","TIMID","CHAOTIC"];
const TYPES = ["normal","fire","water","electric","grass","ice","fighting","poison","ground","flying","psychic","bug","rock","ghost","dragon","dark","steel","fairy"];
const TYPE_LABEL: Record<string,string> = { normal:"Normal",fire:"Fogo",water:"Água",electric:"Elétrico",grass:"Grama",ice:"Gelo",fighting:"Lutador",poison:"Veneno",ground:"Terra",flying:"Voador",psychic:"Psíquico",bug:"Inseto",rock:"Pedra",ghost:"Fantasma",dragon:"Dragão",dark:"Sombrio",steel:"Aço",fairy:"Fada" };

function Field({ label, value, onChange, type="number" }: { label:string; value:string|number; onChange:(value:string)=>void; type?:string }) {
  return <label className="space-y-1 text-[10px] font-bold uppercase tracking-wide text-slate-500"><span>{label}</span><input type={type} value={value} onChange={(e)=>onChange(e.target.value)} className="w-full rounded-lg border border-border bg-slate-950 px-2 py-2 text-xs text-white outline-none focus:border-cyan-400" /></label>;
}

function PlayerMascotsSection() {
  const [playerId,setPlayerId]=useState(""); const [items,setItems]=useState<Mascot[]>([]); const [selected,setSelected]=useState<Mascot|null>(null); const [query,setQuery]=useState(""); const [pending,start]=useTransition(); const [message,setMessage]=useState("");
  const load=(id:string)=>{setPlayerId(id);setSelected(null);if(!id){setItems([]);return;}start(async()=>setItems(await getPlayerMascotEditorData(id)));};
  const shown=items.filter((m)=>`${m.displayName} ${m.speciesName} ${m.pokemonId}`.toLowerCase().includes(query.toLowerCase()));
  const change=(key:keyof Mascot,value:unknown)=>selected&&setSelected({...selected,[key]:value});
  const save=()=>selected&&start(async()=>{const result=await updateMascotAdminAction({mascotId:selected.id,personality:selected.personality,level:Number(selected.level),statForce:Number(selected.statForce),statAgility:Number(selected.statAgility),statCharisma:Number(selected.statCharisma),statInstinct:Number(selected.statInstinct),statVitality:Number(selected.statVitality),randomBonusMin:Number((selected as Mascot & {bonusMin?:number}).bonusMin??0),randomBonusMax:Number((selected as Mascot & {bonusMax?:number}).bonusMax??0)});setMessage(result.error??`Mascote atualizado${result.randomBonus ? ` com ${result.randomBonus} ponto(s) aleatório(s)`:""}.`);if(!result.error)load(playerId);});
  return <div className="space-y-4">
    <div className="grid gap-3 md:grid-cols-2"><PlayerSearchInput value={playerId} onChange={(id)=>load(id)} placeholder="Buscar jogador por nome ou nick..."/><div className="relative"><Search className="absolute left-3 top-2.5 text-slate-500" size={14}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Filtrar mascote por nome ou ID..." className="w-full rounded-xl border border-border bg-slate-950 py-2 pl-9 pr-3 text-xs text-white"/></div></div>
    {pending&&!items.length&&<p className="text-xs text-slate-500">Carregando mascotes...</p>}
    <div className="grid gap-4 xl:grid-cols-[1fr_1.1fr]">
      <div className="max-h-[620px] space-y-2 overflow-y-auto pr-1">{shown.map((m)=><button key={m.id} onClick={()=>setSelected(m)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left ${selected?.id===m.id?"border-cyan-400 bg-cyan-400/10":"border-border bg-slate-950/50 hover:border-slate-600"}`}><img src={m.spriteUrl} alt="" className="h-14 w-14 object-contain [image-rendering:pixelated]"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-white">{m.displayName} · Nv.{m.level}</p><p className="text-[10px] text-slate-400">#{m.pokemonId} · {m.types.map(t=>TYPE_LABEL[t??""]??t).join(" / ")} · {m.personality}</p><p className="text-[10px] text-cyan-300">Total {m.statTotal}{m.eggOriginLabel?` · ${m.eggOriginLabel}`:" · origem não confirmada"}</p></div></button>)}</div>
      <div className="rounded-2xl border border-border bg-slate-950/55 p-4">{selected?<div className="space-y-4"><div><h3 className="font-bold text-white">Editar {selected.displayName}</h3><p className="text-xs text-slate-500">Vitórias {selected.battleWins} · Derrotas {selected.battleLosses} · Felicidade {selected.happiness} · {selected.isShiny?"Shiny · ":""}{selected.isFavorite?"Favorito":"Banco"}</p></div><div className="grid grid-cols-2 gap-2 md:grid-cols-3"><Field label="Nível" value={selected.level} onChange={(v)=>change("level",Number(v))}/><label className="space-y-1 text-[10px] font-bold uppercase text-slate-500"><span>Personalidade</span><select value={selected.personality} onChange={(e)=>change("personality",e.target.value)} className="w-full rounded-lg border border-border bg-slate-950 px-2 py-2 text-xs text-white">{PERSONALITIES.map(p=><option key={p}>{p}</option>)}</select></label>{(["statForce","statAgility","statCharisma","statInstinct","statVitality"] as const).map((key)=><Field key={key} label={{statForce:"Força",statAgility:"Agilidade",statCharisma:"Carisma",statInstinct:"Instinto",statVitality:"Vitalidade"}[key]} value={selected[key]} onChange={(v)=>change(key,Number(v))}/>)}</div><div className="rounded-xl border border-purple-500/20 bg-purple-500/5 p-3"><p className="mb-2 text-xs font-bold text-purple-200">Bônus aleatório opcional</p><p className="mb-3 text-[10px] text-slate-400">Sorteia um total entre o mínimo e máximo e distribui os pontos entre os cinco status.</p><div className="grid grid-cols-2 gap-2"><Field label="Mínimo" value={(selected as Mascot & {bonusMin?:number}).bonusMin??0} onChange={(v)=>change("bonusMin" as keyof Mascot,Number(v))}/><Field label="Máximo" value={(selected as Mascot & {bonusMax?:number}).bonusMax??0} onChange={(v)=>change("bonusMax" as keyof Mascot,Number(v))}/></div></div><button disabled={pending} onClick={save} className="w-full rounded-xl bg-[#FFCB05] py-2.5 text-sm font-black text-slate-950 disabled:opacity-50">Salvar alterações</button>{message&&<p className="text-xs text-cyan-300">{message}</p>}</div>:<p className="text-sm text-slate-500">Selecione um mascote para abrir o relatório e editar.</p>}</div>
    </div>
  </div>;
}

function SpeciesSection() {
  const [query,setQuery]=useState("");const [items,setItems]=useState<Species[]>([]);const [selected,setSelected]=useState<Species|null>(null);const [pending,start]=useTransition();const [message,setMessage]=useState("");
  useEffect(()=>{if(!query.trim()){setItems([]);return;}const timer=setTimeout(()=>start(async()=>setItems(await searchSpeciesAdminAction(query))),220);return()=>clearTimeout(timer);},[query]);
  const set=(key:keyof Species,value:unknown)=>selected&&setSelected({...selected,[key]:value});
  const save=()=>selected&&start(async()=>{const r=await updateSpeciesTypesAdminAction({pokemonId:selected.pokemonId,name:selected.name,generation:selected.generation,primaryType:selected.types[0],secondaryType:selected.types[1]});setMessage(r.error??`${r.affected} mascote(s) existente(s) atualizado(s).`);});
  return <div className="grid gap-4 lg:grid-cols-[1fr_1fr]"><div><div className="relative mb-3"><Search className="absolute left-3 top-2.5 text-slate-500" size={14}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Digite nome ou ID do Pokémon..." className="w-full rounded-xl border border-border bg-slate-950 py-2 pl-9 text-xs text-white"/></div><div className="max-h-[560px] space-y-2 overflow-y-auto">{items.map(s=><button key={s.pokemonId} onClick={()=>setSelected(s)} className="flex w-full items-center gap-3 rounded-xl border border-border bg-slate-950/50 p-3 text-left hover:border-cyan-500"><img src={s.staticSpriteUrl} alt="" className="h-12 w-12 object-contain [image-rendering:pixelated]"/><div><p className="text-sm font-bold text-white">#{s.pokemonId} · {s.name}</p><p className="text-[10px] text-slate-400">Geração {s.generation} · {s.types.map(t=>TYPE_LABEL[t]??t).join(" / ")}{s.custom?" · CUSTOMIZADO":""}</p></div></button>)}</div></div><div className="rounded-2xl border border-border bg-slate-950/55 p-4">{selected?<div className="space-y-4"><div className="flex items-center gap-4"><img src={selected.animatedSpriteUrl} alt="" className="h-24 w-24 object-contain [image-rendering:pixelated]"/><div><h3 className="font-bold text-white">{selected.name}</h3><p className="text-xs text-slate-500">ID {selected.pokemonId} · Geração {selected.generation}</p></div></div><div className="grid grid-cols-2 gap-3">{[0,1].map(i=><label key={i} className="space-y-1 text-[10px] font-bold uppercase text-slate-500"><span>{i?"Tipo secundário":"Tipo principal"}</span><select value={selected.types[i]??""} onChange={(e)=>{const types=[...selected.types];types[i]=e.target.value;set("types",types.filter(Boolean));}} className="w-full rounded-lg border border-border bg-slate-950 px-2 py-2 text-xs text-white">{i===1&&<option value="">Sem segundo tipo</option>}{TYPES.map(t=><option key={t} value={t}>{TYPE_LABEL[t]}</option>)}</select></label>)}</div><p className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-3 text-[11px] text-amber-100">A alteração será aplicada ao catálogo, aos mascotes atuais dessa espécie e usada como override nos novos registros.</p><button disabled={pending} onClick={save} className="w-full rounded-xl bg-cyan-400 py-2.5 text-sm font-black text-slate-950">Aplicar tipo globalmente</button>{message&&<p className="text-xs text-cyan-300">{message}</p>}</div>:<p className="text-sm text-slate-500">Busque e selecione uma espécie.</p>}</div></div>;
}

function CustomSection(){const [pending,start]=useTransition();const [message,setMessage]=useState("");const [form,setForm]=useState({name:"",generation:1,primaryType:"normal",secondaryType:"",rarity:"COMMON",staticSpriteDataUrl:"",animatedSpriteDataUrl:""});const file=(key:"staticSpriteDataUrl"|"animatedSpriteDataUrl",f?:File)=>{if(!f)return;const r=new FileReader();r.onload=()=>setForm(v=>({...v,[key]:String(r.result)}));r.readAsDataURL(f);};const submit=()=>start(async()=>{const r=await createCustomSpeciesAdminAction(form);setMessage(r.error??`Mascote customizado registrado com ID ${r.pokemonId}.`);});return <div className="mx-auto max-w-3xl space-y-4"><div className="grid gap-3 md:grid-cols-2"><Field type="text" label="Nome" value={form.name} onChange={v=>setForm({...form,name:v})}/><Field label="Geração" value={form.generation} onChange={v=>setForm({...form,generation:Number(v)})}/>{["primaryType","secondaryType"].map((key,i)=><label key={key} className="space-y-1 text-[10px] font-bold uppercase text-slate-500"><span>{i?"Tipo secundário":"Tipo principal"}</span><select value={form[key as "primaryType"]} onChange={e=>setForm({...form,[key]:e.target.value})} className="w-full rounded-lg border border-border bg-slate-950 px-2 py-2 text-xs text-white">{i===1&&<option value="">Sem segundo tipo</option>}{TYPES.map(t=><option key={t} value={t}>{TYPE_LABEL[t]}</option>)}</select></label>)}<label className="space-y-1 text-[10px] font-bold uppercase text-slate-500"><span>Classe de raridade</span><select value={form.rarity} onChange={e=>setForm({...form,rarity:e.target.value})} className="w-full rounded-lg border border-border bg-slate-950 px-2 py-2 text-xs text-white">{["COMMON","STARTER","RARE","PSEUDO","PARADOX","LEGENDARY","MYTHICAL"].map(r=><option key={r}>{r}</option>)}</select></label></div><div className="grid gap-3 md:grid-cols-2">{[["staticSpriteDataUrl","Sprite estático (obrigatório)"],["animatedSpriteDataUrl","Sprite animado / GIF (opcional)"]].map(([key,label])=><label key={key} className="rounded-xl border border-dashed border-border bg-slate-950/40 p-4 text-xs text-slate-300"><span className="mb-2 block font-bold">{label}</span><input type="file" accept="image/png,image/webp,image/gif,image/jpeg" onChange={e=>file(key as "staticSpriteDataUrl",e.target.files?.[0])}/>{form[key as "staticSpriteDataUrl"]&&<img src={form[key as "staticSpriteDataUrl"]} alt="Preview" className="mx-auto mt-3 h-24 object-contain [image-rendering:pixelated]"/>}</label>)}</div><p className="text-xs text-slate-400">O arquivo será enviado ao storage da Liga. O novo ID fica reservado no catálogo e a espécie entra na geração informada como mascote customizado.</p><button onClick={submit} disabled={pending||!form.staticSpriteDataUrl} className="w-full rounded-xl bg-purple-500 py-3 text-sm font-black text-white disabled:opacity-40">Registrar mascote customizado</button>{message&&<p className="text-sm text-cyan-300">{message}</p>}</div>}

export function AdminMascotRegistry(){const [tab,setTab]=useState<"players"|"species"|"custom">("players");const tabs=[{id:"players",label:"Mascotes por jogador",icon:UserRoundSearch},{id:"species",label:"Tipos e espécies",icon:Dna},{id:"custom",label:"Mascote customizado",icon:Sparkles}] as const;return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-cyan-400">Administração de mascotes</p><h1 className="mt-1 text-2xl font-black text-white">Catálogo e edição avançada</h1><p className="mt-2 text-sm text-slate-400">Consulte exemplares, corrija espécies globalmente e registre conteúdo customizado.</p></div><div className="flex flex-wrap gap-2">{tabs.map(({id,label,icon:Icon})=><button key={id} onClick={()=>setTab(id)} className={`flex items-center gap-2 rounded-xl border px-4 py-2 text-xs font-bold ${tab===id?"border-[#FFCB05] bg-[#FFCB05]/10 text-[#FFCB05]":"border-border bg-slate-950 text-slate-400"}`}><Icon size={15}/>{label}</button>)}</div><div className="rounded-2xl border border-border bg-slate-900/40 p-4 md:p-5">{tab==="players"?<PlayerMascotsSection/>:tab==="species"?<SpeciesSection/>:<CustomSection/>}</div></div>}
