"use client";
import {useEffect,useState,useTransition} from "react";
import {Check,Copy,Sparkles} from "lucide-react";
import {toast} from "sonner";
import {createLigaCashPayment,getLigaCashOrderStatus} from "./actions";

type PixState={orderId:string;code:string;image?:string;expiresAt:string};
type Confirmation={productLabel:string;creditedLigaCoins:number;isPass:boolean;passActivated:boolean};
const clock=(ms:number)=>{const s=Math.max(0,Math.ceil(ms/1000));return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`};

export function PurchaseButton({code}:{code:string}){
 const[pending,start]=useTransition();const[checkout,setCheckout]=useState(false);const[cpf,setCpf]=useState("");const[email,setEmail]=useState("");const[error,setError]=useState("");const[pix,setPix]=useState<PixState|null>(null);const[confirmation,setConfirmation]=useState<Confirmation|null>(null);const[copied,setCopied]=useState(false);const[now,setNow]=useState(Date.now());
 useEffect(()=>{if(!pix)return;const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[pix]);
 useEffect(()=>{if(!pix)return;let stopped=false;let timer:ReturnType<typeof setTimeout>;const started=Date.now();const check=async()=>{if(document.visibilityState!=="visible"){timer=setTimeout(check,15000);return}const result=await getLigaCashOrderStatus(pix.orderId);if(stopped)return;if(result.status==="PAID"){setConfirmation({productLabel:result.productLabel,creditedLigaCoins:result.creditedLigaCoins,isPass:result.productType==="SUPPORTER_PASS",passActivated:result.passActivated??false});setPix(null);toast.success("Pagamento confirmado!");return}if(["CANCELLED","EXPIRED","REFUNDED"].includes(result.status)){setPix(null);toast.error("Este pedido não está mais aguardando pagamento.");return}timer=setTimeout(check,Date.now()-started<60000?5000:15000)};timer=setTimeout(check,3000);return()=>{stopped=true;clearTimeout(timer)}},[pix]);
 const remaining=pix?new Date(pix.expiresAt).getTime()-now:0;const expired=Boolean(pix&&remaining<=0);
 async function copy(){if(!pix||expired)return;await navigator.clipboard.writeText(pix.code);setCopied(true);toast.success("Código PIX copiado!");setTimeout(()=>setCopied(false),2500)}
 function generate(){setError("");start(async()=>{const result=await createLigaCashPayment(code,cpf,email);if(result.error){setError(result.error);toast.error("O Mercado Pago recusou a cobrança.");return}if(result.orderId&&result.qrCode&&result.expiresAt){setCheckout(false);setPix({orderId:result.orderId,code:result.qrCode,image:result.qrCodeBase64,expiresAt:result.expiresAt});setNow(Date.now())}})}
 return <>
  <button disabled={pending} onClick={()=>{setError("");setCheckout(true)}} className="mt-4 w-full rounded-xl bg-gradient-to-r from-cyan-300 to-violet-400 py-3 font-black text-slate-950 disabled:opacity-50">Comprar com PIX</button>
  {checkout&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/80 p-4" onClick={()=>setCheckout(false)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-md rounded-3xl border border-cyan-300/30 bg-slate-950 p-6"><h2 className="font-pixel text-cyan-300">Identificação do PIX</h2><p className="mt-2 text-sm text-slate-400">E-mail e CPF são enviados diretamente ao Mercado Pago e não são salvos pela Liga. Use dados do pagador, diferentes da conta recebedora.</p><label className="mt-5 block text-xs font-bold text-slate-300">E-mail do pagador<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="pagador@email.com" className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-900 px-4 py-3 text-white"/></label><label className="mt-3 block text-xs font-bold text-slate-300">CPF<input inputMode="numeric" autoComplete="off" value={cpf} onChange={e=>setCpf(e.target.value)} placeholder="000.000.000-00" className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-900 px-4 py-3 text-white"/></label>{error&&<div className="mt-4 rounded-xl border border-red-400/30 bg-red-500/10 p-3 text-xs leading-5 text-red-200">{error}</div>}<button disabled={pending||cpf.replace(/\D/g,"").length!==11||!email.includes("@")} onClick={generate} className="mt-4 w-full rounded-xl bg-cyan-300 py-3 font-black text-slate-950 disabled:opacity-40">{pending?"Gerando...":"Gerar QR Code"}</button><button onClick={()=>setCheckout(false)} className="mt-3 w-full text-xs text-slate-500">Cancelar</button></div></div>}
  {pix&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/80 p-4" onClick={()=>setPix(null)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-md rounded-3xl border border-cyan-300/30 bg-slate-950 p-6 text-center"><h2 className="font-pixel text-cyan-300">PIX gerado</h2><p className="mt-2 text-sm text-slate-400">O crédito acontece automaticamente após a confirmação.</p><div className={`mx-auto mt-3 w-fit rounded-full px-3 py-1 text-xs font-bold ${expired?"bg-red-500/10 text-red-300":"bg-emerald-500/10 text-emerald-300"}`}>{expired?"QR Code expirado":`Válido por ${clock(remaining)}`}</div>{pix.image&&<img src={`data:image/png;base64,${pix.image}`} alt="QR Code PIX" className={`mx-auto my-5 h-64 w-64 rounded-2xl bg-white p-3 ${expired?"opacity-30 grayscale":""}`}/>}<button disabled={expired} onClick={copy} className="flex w-full items-center justify-center gap-2 rounded-xl border border-cyan-300/30 px-3 py-3 text-sm font-bold text-cyan-200 disabled:text-slate-600">{copied?<><Check size={17}/>Copiado!</>:<><Copy size={17}/>Copiar código PIX</>}</button>{expired&&<p className="mt-2 text-xs text-red-300">Feche e gere uma nova cobrança.</p>}<button onClick={()=>setPix(null)} className="mt-3 text-xs text-slate-500">Fechar</button></div></div>}
  {confirmation&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/85 p-4" onClick={()=>setConfirmation(null)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-md overflow-hidden rounded-3xl border border-emerald-300/40 bg-[radial-gradient(circle_at_top,rgba(34,211,238,.2),transparent_42%),#020617] p-7 text-center shadow-2xl shadow-cyan-500/10"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full border border-emerald-300/40 bg-emerald-400/10 text-emerald-300"><Check size={34}/></div><div className="mt-4 flex items-center justify-center gap-2 text-cyan-200"><Sparkles size={16}/><span className="text-xs font-black uppercase tracking-[.2em]">Pagamento confirmado</span><Sparkles size={16}/></div><h2 className="mt-3 text-2xl font-black text-white">Obrigado por apoiar a Liga!</h2>{confirmation.isPass?<p className="mt-3 text-sm leading-6 text-slate-300">Seu pagamento de <strong className="text-amber-200">{confirmation.productLabel}</strong> foi reconhecido. {confirmation.passActivated?"O passe atual já está ativo na sua conta.":"Você entrou na lista de distribuição do próximo passe."}</p>:<><p className="mt-3 text-sm text-slate-300">As LigaCoins já foram adicionadas à sua carteira.</p><strong className="mt-4 block text-4xl text-cyan-200">+{confirmation.creditedLigaCoins.toLocaleString("pt-BR")} LC</strong></>}<button onClick={()=>{setConfirmation(null);window.location.reload()}} className="mt-6 w-full rounded-xl bg-gradient-to-r from-cyan-300 to-emerald-300 py-3 font-black text-slate-950">Continuar</button></div></div>}
 </>
}
