ALTER TABLE "arena_draft_presets"
  ADD COLUMN IF NOT EXISTS "source" TEXT NOT NULL DEFAULT 'CUSTOM';
ALTER TABLE "arena_draft_matches"
  ADD COLUMN IF NOT EXISTS "mode" TEXT NOT NULL DEFAULT 'CUSTOM';
