// GERADO por scripts/generate-ability-data.py a partir de docs/habilidades-passivas-mascotes.xlsx. Não editar à mão.
export type AbilityEffectDef = { name: string; category: string; trigger: string; text: string; activations: number; scale: string | null; min: number | null; max: number | null };
export type AbilityDef = { name: string; effect?: string; param?: string; o?: { activations?: number; min?: number; max?: number } };

export const ABILITY_EFFECTS: Record<string, AbilityEffectDef> = {
  FURIA_TIPO: {"name":"Fúria elemental","category":"Dano","trigger":"HP baixo (abaixo de 33%)","text":"Se o mascote tem o tipo {T}, seus golpes causam {rng} mais dano.","activations":2,"scale":"Força","min":8,"max":20},
  FURIA: {"name":"Fúria","category":"Dano","trigger":"HP baixo (abaixo de 33%)","text":"Os golpes causam {rng} mais dano.","activations":2,"scale":"Força","min":6,"max":18},
  MAESTRIA_TIPO: {"name":"Maestria elemental","category":"Dano","trigger":"Ao atacar","text":"Se o mascote tem o tipo {T}, seus golpes causam {rng} mais dano.","activations":2,"scale":"Força","min":6,"max":20},
  MAESTRIA_GOLPE: {"name":"Maestria de golpe","category":"Dano","trigger":"Ao atacar","text":"Golpes {T} causam {rng} mais dano.","activations":2,"scale":"Força","min":6,"max":20},
  PODER_BRUTO: {"name":"Poder bruto","category":"Dano","trigger":"Ao atacar","text":"Nas duas primeiras ações, o golpe causa {rng} mais dano.","activations":2,"scale":"Força","min":8,"max":20},
  VANTAGEM: {"name":"Vantagem ampliada","category":"Dano","trigger":"Ao atacar","text":"Golpes com vantagem de tipo causam {rng} mais dano.","activations":2,"scale":"Instinto","min":6,"max":20},
  LENTE: {"name":"Lente colorida","category":"Dano","trigger":"Ao atacar","text":"Golpes com resistência de tipo perdem menos dano: {rng} a mais.","activations":2,"scale":"Instinto","min":6,"max":20},
  QUEBRA_GUARDA: {"name":"Quebra-defesas","category":"Dano","trigger":"Ao atacar","text":"Ignora {rng} da mitigação (Vitalidade) do alvo.","activations":2,"scale":"Instinto","min":6,"max":20},
  EMBALO: {"name":"Embalo","category":"Dano","trigger":"Ao dar K.O.","text":"Depois de derrotar um rival, o próximo golpe causa {rng} mais dano.","activations":2,"scale":"Força","min":8,"max":20},
  VINGANCA: {"name":"Vingança","category":"Dano","trigger":"Aliado cai","text":"Quando um aliado cai, o próximo golpe causa {rng} mais dano.","activations":1,"scale":"Força","min":8,"max":20},
  ADVERSIDADE: {"name":"Adversidade","category":"Dano","trigger":"Ao receber debuff","text":"Ao ter um atributo reduzido, o próximo golpe causa {rng} mais dano.","activations":2,"scale":"Força","min":8,"max":20},
  GOLPE_DUPLO: {"name":"Golpe duplo","category":"Dano","trigger":"Ao atacar","text":"O golpe ganha um segundo impacto de {rng} do dano.","activations":2,"scale":"Força","min":6,"max":20},
  ULTIMO: {"name":"Último a agir","category":"Dano","trigger":"Ao atacar","text":"Ao agir depois dos aliados na rodada, o golpe causa {rng} mais dano.","activations":2,"scale":"Instinto","min":6,"max":20},
  ANALISE: {"name":"Análise","category":"Dano","trigger":"Início da luta","text":"O primeiro golpe contra o rival de menor Vitalidade causa {rng} mais dano.","activations":1,"scale":"Instinto","min":6,"max":20},
  REVIDE: {"name":"Revide","category":"Dano","trigger":"Ao ser atingido","text":"Depois de ser atingido, o próximo golpe causa {rng} mais dano.","activations":3,"scale":"Força","min":6,"max":20},
  PELAGEM: {"name":"Pelagem elemental","category":"Defesa","trigger":"Ao ser atingido","text":"Golpes {T} causam {rng} menos dano.","activations":3,"scale":"Vitalidade","min":6,"max":20},
  ABSORCAO: {"name":"Absorção","category":"Defesa","trigger":"Ao ser atingido","text":"Golpes do tipo {T} causam {rng} menos dano e curam 5% do HP máximo.","activations":3,"scale":"Vitalidade","min":6,"max":20},
  PARARAIO: {"name":"Para-raios","category":"Defesa","trigger":"Ao desviar","text":"Golpes do tipo {T} contra aliados são redirecionados a este mascote, que recebe {rng} menos dano deles.","activations":3,"scale":"Carisma","min":6,"max":20},
  PREPARO: {"name":"Postura firme","category":"Defesa","trigger":"Ao preparar defesa","text":"Ao preparar defesa (Defensor), reduz {rng} extra do próximo golpe.","activations":2,"scale":"Vitalidade","min":6,"max":20},
  GUARDA: {"name":"Guarda de aliados","category":"Defesa","trigger":"Ao proteger","text":"Quando o Guardião protege um aliado, o golpe causa {rng} menos dano.","activations":3,"scale":"Vitalidade","min":6,"max":20},
  ARMADURA: {"name":"Armadura de tipos","category":"Defesa","trigger":"Ao ser atingido","text":"Golpes com vantagem de tipo contra este mascote causam {rng} menos dano.","activations":3,"scale":"Vitalidade","min":6,"max":20},
  ESCAMAS: {"name":"Escamas","category":"Defesa","trigger":"Ao ser atingido","text":"O primeiro golpe recebido com HP cheio causa {rng} menos dano.","activations":1,"scale":"Vitalidade","min":8,"max":20},
  CORPO_LIMPO: {"name":"Corpo limpo","category":"Defesa","trigger":"Ao receber debuff","text":"Debuffs recebidos ficam {rng} menores.","activations":3,"scale":"Vitalidade","min":8,"max":20},
  ESPELHO: {"name":"Espelho","category":"Defesa","trigger":"Ao receber debuff","text":"Devolve {rng} do debuff recebido a quem o aplicou.","activations":2,"scale":"Instinto","min":6,"max":20},
  GUARDA_PERFEITA: {"name":"Guarda perfeita","category":"Defesa","trigger":"Ao ser atingido","text":"Golpes sem vantagem de tipo causam {rng} menos dano.","activations":2,"scale":"Vitalidade","min":8,"max":20},
  RETIRADA: {"name":"Retirada","category":"Defesa","trigger":"HP baixo (abaixo de 50%)","text":"O próximo golpe recebido causa {rng} menos dano.","activations":1,"scale":"Vitalidade","min":8,"max":20},
  NEGAR_BUFF: {"name":"Ignorar bônus","category":"Defesa","trigger":"Ao ser atingido","text":"Ignora {rng} dos bônus de buff (Encorajador, Batedor) do atacante.","activations":3,"scale":"Instinto","min":6,"max":20},
  CASCO: {"name":"Casco","category":"Defesa","trigger":"Ao ser atingido","text":"Golpes causam {rng} menos dano.","activations":3,"scale":"Vitalidade","min":4,"max":12},
  EVASIVA: {"name":"Evasiva","category":"Defesa","trigger":"Ao ser atingido","text":"Esquiva parcial: o golpe causa {rng} menos dano.","activations":3,"scale":"Agilidade","min":4,"max":12},
  IMUNE_INDIRETO: {"name":"Sem efeito colateral","category":"Defesa","trigger":"Passivo","text":"Não sofre dano de reflexo (Espinhos, Último suspiro) nem de efeitos indiretos de habilidades.","activations":0,"scale":null,"min":null,"max":null},
  ESPINHOS: {"name":"Espinhos","category":"Reflexo","trigger":"Ao ser atingido","text":"Devolve {rng} do dano recebido ao atacante (mínimo 1).","activations":3,"scale":"Vitalidade","min":6,"max":20},
  ULTIMO_SUSPIRO: {"name":"Último suspiro","category":"Reflexo","trigger":"Ao ser derrotado","text":"Ao cair, causa {rng} do HP máximo dele ao último atacante.","activations":1,"scale":"Vitalidade","min":8,"max":20},
  REACAO: {"name":"Reação de contato","category":"Controle","trigger":"Ao ser atingido","text":"30% de chance de reduzir {S} do atacante em {rng}.","activations":2,"scale":"Instinto","min":6,"max":20},
  TOQUE: {"name":"Toque debilitante","category":"Controle","trigger":"Ao atacar","text":"30% de chance de reduzir {S} do alvo em {rng}.","activations":2,"scale":"Instinto","min":6,"max":20},
  INTIMIDACAO: {"name":"Intimidação","category":"Controle","trigger":"Início da luta","text":"Reduz {S} de todos os rivais em {rng}.","activations":1,"scale":"Carisma","min":4,"max":12},
  IMPULSO: {"name":"Impulso","category":"Suporte","trigger":"Início da rodada","text":"Nas 3 primeiras rodadas, ganha Agilidade, até {rng} no total.","activations":3,"scale":"Agilidade","min":4,"max":12},
  PURIFICACAO: {"name":"Purificação","category":"Suporte","trigger":"Ao remover debuff","text":"No início da rodada, reduz em {rng} o maior debuff do próprio mascote.","activations":2,"scale":"Carisma","min":6,"max":20},
  PURIFICACAO_GRUPO: {"name":"Cura em grupo","category":"Suporte","trigger":"Ao remover debuff","text":"No início da rodada, reduz em {rng} o maior debuff de um aliado.","activations":2,"scale":"Carisma","min":6,"max":20},
  CURA_GRADUAL: {"name":"Cura gradual","category":"Suporte","trigger":"Início da rodada","text":"Cura {rng} do HP máximo.","activations":3,"scale":"Vitalidade","min":3,"max":10},
  REGENERACAO: {"name":"Regeneração","category":"Suporte","trigger":"HP baixo (abaixo de 50%)","text":"Recupera {rng} do HP máximo.","activations":1,"scale":"Vitalidade","min":8,"max":20},
  CURA_ALIADO: {"name":"Hospitalidade","category":"Suporte","trigger":"Início da luta","text":"Cura {rng} do HP máximo de um aliado.","activations":1,"scale":"Carisma","min":8,"max":20},
  REFORCO: {"name":"Reforço","category":"Suporte","trigger":"Ao aplicar buff","text":"O buff dado a aliados (Encorajador, Batedor ou cura) fica {rng} maior.","activations":2,"scale":"Carisma","min":6,"max":20},
  AURA: {"name":"Aura","category":"Suporte","trigger":"Ao atacar","text":"Aliados do tipo {T} causam {rng} mais dano.","activations":2,"scale":"Carisma","min":4,"max":12},
  AMBIENTE: {"name":"Ambiente","category":"Suporte","trigger":"Início da luta","text":"Nas 3 primeiras rodadas, aliados do tipo {T} causam {rng} mais dano.","activations":3,"scale":"Instinto","min":4,"max":12},
  VEU: {"name":"Véu","category":"Suporte","trigger":"Ao receber debuff","text":"Debuffs recebidos pelos aliados ficam {rng} menores.","activations":2,"scale":"Carisma","min":6,"max":20},
  RESISTENCIA: {"name":"Resistência","category":"Sobrevivência","trigger":"Ao ser atingido","text":"Uma vez por luta, sobrevive a um golpe fatal com 1 HP se estiver com HP cheio.","activations":1,"scale":null,"min":null,"max":null},
};

export const ABILITIES: Record<string, AbilityDef> = {
  "adaptability": {"name":"Adaptability","effect":"VANTAGEM"},
  "aerilate": {"name":"Aerilate","effect":"MAESTRIA_TIPO","param":"Voador"},
  "aftermath": {"name":"Aftermath","effect":"ULTIMO_SUSPIRO"},
  "air-lock": {"name":"Air Lock"},
  "analytic": {"name":"Analytic","effect":"ULTIMO"},
  "anger-point": {"name":"Anger Point","effect":"FURIA"},
  "anger-shell": {"name":"Anger Shell","effect":"FURIA"},
  "anticipation": {"name":"Anticipation"},
  "arena-trap": {"name":"Arena Trap"},
  "armor-tail": {"name":"Armor Tail","effect":"INTIMIDACAO","param":"Agilidade"},
  "aroma-veil": {"name":"Aroma Veil","effect":"VEU"},
  "as-one-glastrier": {"name":"As One","effect":"EMBALO"},
  "as-one-spectrier": {"name":"As One","effect":"EMBALO"},
  "aura-break": {"name":"Aura Break"},
  "aura-guard": {"name":"Aura Guard","effect":"CASCO"},
  "bad-dreams": {"name":"Bad Dreams"},
  "ball-fetch": {"name":"Ball Fetch"},
  "battery": {"name":"Battery","effect":"REFORCO"},
  "battle-armor": {"name":"Battle Armor","effect":"CASCO"},
  "battle-bond": {"name":"Battle Bond","effect":"EMBALO"},
  "beads-of-ruin": {"name":"Beads of Ruin","effect":"INTIMIDACAO","param":"Agilidade"},
  "beast-boost": {"name":"Beast Boost","effect":"EMBALO"},
  "berserk": {"name":"Berserk","effect":"FURIA"},
  "big-pecks": {"name":"Big Pecks","effect":"CORPO_LIMPO"},
  "blaze": {"name":"Blaze","effect":"FURIA_TIPO","param":"Fogo"},
  "bulletproof": {"name":"Bulletproof","effect":"CASCO"},
  "cheek-pouch": {"name":"Cheek Pouch","effect":"CURA_GRADUAL"},
  "chilling-neigh": {"name":"Chilling Neigh","effect":"EMBALO"},
  "chlorophyll": {"name":"Chlorophyll","effect":"IMPULSO"},
  "clear-body": {"name":"Clear Body","effect":"CORPO_LIMPO"},
  "cloud-nine": {"name":"Cloud Nine"},
  "color-change": {"name":"Color Change"},
  "comatose": {"name":"Comatose"},
  "commander": {"name":"Commander"},
  "competitive": {"name":"Competitive","effect":"ADVERSIDADE"},
  "compound-eyes": {"name":"Compound Eyes","effect":"QUEBRA_GUARDA"},
  "contrary": {"name":"Contrary"},
  "corrosion": {"name":"Corrosion","effect":"TOQUE","param":"Vitalidade"},
  "costar": {"name":"Costar","effect":"REFORCO"},
  "cotton-down": {"name":"Cotton Down","effect":"REACAO","param":"Agilidade"},
  "cud-chew": {"name":"Cud Chew","effect":"CURA_GRADUAL"},
  "cursed-body": {"name":"Cursed Body","effect":"REACAO","param":"Instinto"},
  "cute-charm": {"name":"Cute Charm","effect":"REACAO","param":"Força"},
  "damp": {"name":"Damp"},
  "dancer": {"name":"Dancer"},
  "dark-aura": {"name":"Dark Aura","effect":"AURA","param":"Sombrio"},
  "dauntless-shield": {"name":"Dauntless Shield","effect":"PREPARO"},
  "dazzling": {"name":"Dazzling","effect":"INTIMIDACAO","param":"Agilidade"},
  "defeatist": {"name":"Defeatist"},
  "defiant": {"name":"Defiant","effect":"ADVERSIDADE"},
  "delta-stream": {"name":"Delta Stream","effect":"AMBIENTE","param":"Voador"},
  "desolate-land": {"name":"Desolate Land","effect":"AMBIENTE","param":"Fogo"},
  "disguise": {"name":"Disguise","effect":"ESCAMAS"},
  "download": {"name":"Download","effect":"ANALISE"},
  "dragonize": {"name":"Dragonize","effect":"MAESTRIA_TIPO","param":"Dragão"},
  "dragons-maw": {"name":"Dragon’s Maw","effect":"MAESTRIA_TIPO","param":"Dragão"},
  "drizzle": {"name":"Drizzle","effect":"AMBIENTE","param":"Água"},
  "drought": {"name":"Drought","effect":"AMBIENTE","param":"Fogo"},
  "dry-skin": {"name":"Dry Skin","effect":"CURA_GRADUAL"},
  "early-bird": {"name":"Early Bird"},
  "earth-eater": {"name":"Earth Eater","effect":"ABSORCAO","param":"Terra"},
  "eelevate": {"name":"Eelevate","effect":"ABSORCAO","param":"Terra"},
  "effect-spore": {"name":"Effect Spore","effect":"REACAO","param":"Instinto"},
  "electric-surge": {"name":"Electric Surge","effect":"AMBIENTE","param":"Elétrico"},
  "electromorphosis": {"name":"Electromorphosis","effect":"REVIDE"},
  "emergency-exit": {"name":"Emergency Exit","effect":"RETIRADA"},
  "fairy-aura": {"name":"Fairy Aura","effect":"AURA","param":"Fada"},
  "filter": {"name":"Filter","effect":"ARMADURA"},
  "fire-mane": {"name":"Fire Mane","effect":"MAESTRIA_TIPO","param":"Fogo"},
  "flame-body": {"name":"Flame Body","effect":"REACAO","param":"Força"},
  "flare-boost": {"name":"Flare Boost","effect":"ADVERSIDADE"},
  "flash-fire": {"name":"Flash Fire","effect":"ABSORCAO","param":"Fogo"},
  "flower-gift": {"name":"Flower Gift","effect":"REFORCO"},
  "flower-veil": {"name":"Flower Veil","effect":"VEU"},
  "fluffy": {"name":"Fluffy","effect":"CASCO"},
  "forecast": {"name":"Forecast"},
  "forewarn": {"name":"Forewarn"},
  "friend-guard": {"name":"Friend Guard","effect":"GUARDA"},
  "frisk": {"name":"Frisk"},
  "full-metal-body": {"name":"Full Metal Body","effect":"CORPO_LIMPO"},
  "fur-coat": {"name":"Fur Coat","effect":"CASCO"},
  "gale-wings": {"name":"Gale Wings","effect":"IMPULSO"},
  "gluttony": {"name":"Gluttony"},
  "good-as-gold": {"name":"Good as Gold","effect":"CORPO_LIMPO"},
  "gooey": {"name":"Gooey","effect":"REACAO","param":"Agilidade"},
  "gorilla-tactics": {"name":"Gorilla Tactics","effect":"PODER_BRUTO"},
  "grass-pelt": {"name":"Grass Pelt","effect":"PREPARO"},
  "grassy-surge": {"name":"Grassy Surge","effect":"AMBIENTE","param":"Planta"},
  "grim-neigh": {"name":"Grim Neigh","effect":"EMBALO"},
  "guard-dog": {"name":"Guard Dog","effect":"ADVERSIDADE"},
  "gulp-missile": {"name":"Gulp Missile"},
  "guts": {"name":"Guts","effect":"ADVERSIDADE"},
  "hadron-engine": {"name":"Hadron Engine","effect":"AMBIENTE","param":"Elétrico"},
  "harvest": {"name":"Harvest","effect":"CURA_GRADUAL"},
  "healer": {"name":"Healer","effect":"PURIFICACAO_GRUPO"},
  "heatproof": {"name":"Heatproof","effect":"PELAGEM","param":"do tipo Fogo"},
  "heavy-metal": {"name":"Heavy Metal"},
  "honey-gather": {"name":"Honey Gather"},
  "hospitality": {"name":"Hospitality","effect":"CURA_ALIADO"},
  "huge-power": {"name":"Huge Power","effect":"PODER_BRUTO"},
  "hunger-switch": {"name":"Hunger Switch"},
  "hustle": {"name":"Hustle","effect":"PODER_BRUTO"},
  "hydration": {"name":"Hydration","effect":"PURIFICACAO"},
  "hyper-cutter": {"name":"Hyper Cutter","effect":"CORPO_LIMPO"},
  "ice-body": {"name":"Ice Body","effect":"CURA_GRADUAL"},
  "ice-face": {"name":"Ice Face","effect":"ESCAMAS"},
  "ice-scales": {"name":"Ice Scales","effect":"CASCO"},
  "illuminate": {"name":"Illuminate"},
  "illusion": {"name":"Illusion"},
  "immunity": {"name":"Immunity","effect":"CORPO_LIMPO"},
  "imposter": {"name":"Imposter"},
  "infiltrator": {"name":"Infiltrator","effect":"QUEBRA_GUARDA"},
  "innards-out": {"name":"Innards Out","effect":"ULTIMO_SUSPIRO"},
  "inner-focus": {"name":"Inner Focus","effect":"CORPO_LIMPO"},
  "insomnia": {"name":"Insomnia","effect":"CORPO_LIMPO"},
  "intimidate": {"name":"Intimidate","effect":"INTIMIDACAO","param":"Força"},
  "intrepid-sword": {"name":"Intrepid Sword","effect":"PODER_BRUTO"},
  "iron-barbs": {"name":"Iron Barbs","effect":"ESPINHOS"},
  "iron-fist": {"name":"Iron Fist","effect":"MAESTRIA_GOLPE","param":"de soco"},
  "justified": {"name":"Justified","effect":"REVIDE"},
  "keen-eye": {"name":"Keen Eye","effect":"CORPO_LIMPO"},
  "klutz": {"name":"Klutz"},
  "leaf-guard": {"name":"Leaf Guard","effect":"CORPO_LIMPO"},
  "levitate": {"name":"Levitate","effect":"ABSORCAO","param":"Terra"},
  "libero": {"name":"Libero"},
  "light-metal": {"name":"Light Metal"},
  "lightning-rod": {"name":"Lightning Rod","effect":"PARARAIO","param":"Elétrico"},
  "limber": {"name":"Limber","effect":"CORPO_LIMPO"},
  "lingering-aroma": {"name":"Lingering Aroma","effect":"REACAO","param":"Instinto"},
  "liquid-ooze": {"name":"Liquid Ooze","effect":"ESPINHOS"},
  "liquid-voice": {"name":"Liquid Voice","effect":"MAESTRIA_TIPO","param":"Água"},
  "long-reach": {"name":"Long Reach","effect":"QUEBRA_GUARDA"},
  "magic-bounce": {"name":"Magic Bounce","effect":"ESPELHO"},
  "magic-guard": {"name":"Magic Guard","effect":"IMUNE_INDIRETO"},
  "magician": {"name":"Magician"},
  "magma-armor": {"name":"Magma Armor","effect":"CORPO_LIMPO"},
  "magnet-pull": {"name":"Magnet Pull"},
  "marvel-scale": {"name":"Marvel Scale","effect":"PREPARO"},
  "mega-launcher": {"name":"Mega Launcher","effect":"MAESTRIA_GOLPE","param":"de pulso e aura"},
  "mega-sol": {"name":"Mega Sol","effect":"AMBIENTE","param":"Fogo"},
  "merciless": {"name":"Merciless","effect":"QUEBRA_GUARDA"},
  "mimicry": {"name":"Mimicry"},
  "minds-eye": {"name":"Mind’s Eye","effect":"QUEBRA_GUARDA"},
  "minus": {"name":"Minus","effect":"REFORCO"},
  "mirror-armor": {"name":"Mirror Armor","effect":"ESPELHO"},
  "misty-surge": {"name":"Misty Surge","effect":"AMBIENTE","param":"Fada"},
  "mold-breaker": {"name":"Mold Breaker","effect":"QUEBRA_GUARDA"},
  "moody": {"name":"Moody","effect":"IMPULSO"},
  "motor-drive": {"name":"Motor Drive","effect":"ABSORCAO","param":"Elétrico"},
  "moxie": {"name":"Moxie","effect":"EMBALO"},
  "multiscale": {"name":"Multiscale","effect":"ESCAMAS"},
  "multitype": {"name":"Multitype"},
  "mummy": {"name":"Mummy","effect":"REACAO","param":"Instinto"},
  "mycelium-might": {"name":"Mycelium Might"},
  "natural-cure": {"name":"Natural Cure","effect":"PURIFICACAO"},
  "neuroforce": {"name":"Neuroforce","effect":"VANTAGEM"},
  "neutralizing-gas": {"name":"Neutralizing Gas"},
  "no-guard": {"name":"No Guard","effect":"QUEBRA_GUARDA"},
  "normalize": {"name":"Normalize"},
  "oblivious": {"name":"Oblivious","effect":"CORPO_LIMPO"},
  "opportunist": {"name":"Opportunist"},
  "orichalcum-pulse": {"name":"Orichalcum Pulse","effect":"AMBIENTE","param":"Fogo"},
  "overcoat": {"name":"Overcoat","effect":"CASCO"},
  "overgrow": {"name":"Overgrow","effect":"FURIA_TIPO","param":"Planta"},
  "own-tempo": {"name":"Own Tempo","effect":"CORPO_LIMPO"},
  "parental-bond": {"name":"Parental Bond","effect":"GOLPE_DUPLO"},
  "perish-body": {"name":"Perish Body","effect":"ESPINHOS"},
  "pickpocket": {"name":"Pickpocket"},
  "pickup": {"name":"Pickup"},
  "piercing-drill": {"name":"Piercing Drill","effect":"QUEBRA_GUARDA"},
  "pixilate": {"name":"Pixilate","effect":"MAESTRIA_TIPO","param":"Fada"},
  "plus": {"name":"Plus","effect":"REFORCO"},
  "poison-heal": {"name":"Poison Heal","effect":"CURA_GRADUAL"},
  "poison-point": {"name":"Poison Point","effect":"REACAO","param":"Vitalidade"},
  "poison-puppeteer": {"name":"Poison Puppeteer","effect":"TOQUE","param":"Instinto"},
  "poison-touch": {"name":"Poison Touch","effect":"TOQUE","param":"Vitalidade"},
  "power-construct": {"name":"Power Construct"},
  "power-spot": {"name":"Power Spot","effect":"REFORCO"},
  "prankster": {"name":"Prankster","effect":"IMPULSO"},
  "pressure": {"name":"Pressure","effect":"INTIMIDACAO","param":"Instinto"},
  "primordial-sea": {"name":"Primordial Sea","effect":"AMBIENTE","param":"Água"},
  "prism-armor": {"name":"Prism Armor","effect":"ARMADURA"},
  "propeller-tail": {"name":"Propeller Tail"},
  "protean": {"name":"Protean"},
  "protosynthesis": {"name":"Protosynthesis","effect":"PODER_BRUTO"},
  "psychic-surge": {"name":"Psychic Surge","effect":"AMBIENTE","param":"Psíquico"},
  "punk-rock": {"name":"Punk Rock","effect":"MAESTRIA_GOLPE","param":"sonoros"},
  "pure-power": {"name":"Pure Power","effect":"PODER_BRUTO"},
  "purifying-salt": {"name":"Purifying Salt","effect":"CORPO_LIMPO"},
  "quark-drive": {"name":"Quark Drive","effect":"PODER_BRUTO"},
  "queenly-majesty": {"name":"Queenly Majesty","effect":"INTIMIDACAO","param":"Agilidade"},
  "quick-feet": {"name":"Quick Feet","effect":"ADVERSIDADE"},
  "rain-dish": {"name":"Rain Dish","effect":"CURA_GRADUAL"},
  "rattled": {"name":"Rattled","effect":"IMPULSO"},
  "receiver": {"name":"Receiver","effect":"VINGANCA"},
  "reckless": {"name":"Reckless","effect":"MAESTRIA_GOLPE","param":"com recuo"},
  "refrigerate": {"name":"Refrigerate","effect":"MAESTRIA_TIPO","param":"Gelo"},
  "regenerator": {"name":"Regenerator","effect":"REGENERACAO"},
  "ripen": {"name":"Ripen"},
  "rivalry": {"name":"Rivalry"},
  "rks-system": {"name":"RKS System"},
  "rock-head": {"name":"Rock Head","effect":"CASCO"},
  "rocky-payload": {"name":"Rocky Payload","effect":"MAESTRIA_TIPO","param":"Pedra"},
  "rough-skin": {"name":"Rough Skin","effect":"ESPINHOS"},
  "run-away": {"name":"Run Away"},
  "sand-force": {"name":"Sand Force","effect":"MAESTRIA_TIPO","param":"Pedra"},
  "sand-rush": {"name":"Sand Rush","effect":"IMPULSO"},
  "sand-spit": {"name":"Sand Spit"},
  "sand-stream": {"name":"Sand Stream","effect":"AMBIENTE","param":"Pedra"},
  "sand-veil": {"name":"Sand Veil","effect":"EVASIVA"},
  "sap-sipper": {"name":"Sap Sipper","effect":"ABSORCAO","param":"Planta"},
  "schooling": {"name":"Schooling"},
  "scrappy": {"name":"Scrappy","effect":"QUEBRA_GUARDA"},
  "screen-cleaner": {"name":"Screen Cleaner"},
  "seed-sower": {"name":"Seed Sower","effect":"AMBIENTE","param":"Planta"},
  "serene-grace": {"name":"Serene Grace"},
  "shadow-shield": {"name":"Shadow Shield","effect":"ESCAMAS"},
  "shadow-tag": {"name":"Shadow Tag"},
  "sharpness": {"name":"Sharpness","effect":"MAESTRIA_GOLPE","param":"cortantes"},
  "shed-skin": {"name":"Shed Skin","effect":"PURIFICACAO"},
  "sheer-force": {"name":"Sheer Force","effect":"MAESTRIA_GOLPE","param":"diretos"},
  "shell-armor": {"name":"Shell Armor","effect":"CASCO"},
  "shield-dust": {"name":"Shield Dust","effect":"CORPO_LIMPO"},
  "shields-down": {"name":"Shields Down"},
  "simple": {"name":"Simple"},
  "skill-link": {"name":"Skill Link","effect":"GOLPE_DUPLO"},
  "slow-start": {"name":"Slow Start"},
  "slush-rush": {"name":"Slush Rush","effect":"IMPULSO"},
  "sniper": {"name":"Sniper","effect":"QUEBRA_GUARDA"},
  "snow-cloak": {"name":"Snow Cloak","effect":"EVASIVA"},
  "snow-warning": {"name":"Snow Warning","effect":"AMBIENTE","param":"Gelo"},
  "solar-power": {"name":"Solar Power","effect":"PODER_BRUTO"},
  "solid-rock": {"name":"Solid Rock","effect":"ARMADURA"},
  "soul-heart": {"name":"Soul-Heart","effect":"VINGANCA"},
  "soundproof": {"name":"Soundproof","effect":"CORPO_LIMPO"},
  "speed-boost": {"name":"Speed Boost","effect":"IMPULSO"},
  "spicy-spray": {"name":"Spicy Spray","effect":"ESPINHOS"},
  "stakeout": {"name":"Stakeout","effect":"QUEBRA_GUARDA"},
  "stall": {"name":"Stall"},
  "stalwart": {"name":"Stalwart"},
  "stamina": {"name":"Stamina","effect":"PREPARO"},
  "stance-change": {"name":"Stance Change"},
  "static": {"name":"Static","effect":"REACAO","param":"Agilidade"},
  "steadfast": {"name":"Steadfast"},
  "steam-engine": {"name":"Steam Engine","effect":"REVIDE"},
  "steelworker": {"name":"Steelworker","effect":"MAESTRIA_TIPO","param":"Aço"},
  "steely-spirit": {"name":"Steely Spirit","effect":"AURA","param":"Aço"},
  "stench": {"name":"Stench","effect":"TOQUE","param":"Instinto"},
  "sticky-hold": {"name":"Sticky Hold"},
  "storm-drain": {"name":"Storm Drain","effect":"PARARAIO","param":"Água"},
  "strong-jaw": {"name":"Strong Jaw","effect":"MAESTRIA_GOLPE","param":"de mordida"},
  "sturdy": {"name":"Sturdy","effect":"RESISTENCIA"},
  "suction-cups": {"name":"Suction Cups"},
  "super-luck": {"name":"Super Luck","effect":"QUEBRA_GUARDA"},
  "supersweet-syrup": {"name":"Supersweet Syrup","effect":"INTIMIDACAO","param":"Agilidade"},
  "supreme-overlord": {"name":"Supreme Overlord","effect":"VINGANCA"},
  "swarm": {"name":"Swarm","effect":"FURIA_TIPO","param":"Inseto"},
  "sweet-veil": {"name":"Sweet Veil","effect":"VEU"},
  "swift-swim": {"name":"Swift Swim","effect":"IMPULSO"},
  "sword-of-ruin": {"name":"Sword of Ruin","effect":"INTIMIDACAO","param":"Vitalidade"},
  "symbiosis": {"name":"Symbiosis","effect":"REFORCO"},
  "synchronize": {"name":"Synchronize","effect":"ESPELHO"},
  "tablets-of-ruin": {"name":"Tablets of Ruin","effect":"INTIMIDACAO","param":"Força"},
  "tangled-feet": {"name":"Tangled Feet","effect":"EVASIVA"},
  "technician": {"name":"Technician","effect":"MAESTRIA_GOLPE","param":"de baixo dano"},
  "telepathy": {"name":"Telepathy"},
  "tera-shell": {"name":"Tera Shell","effect":"ARMADURA"},
  "tera-shift": {"name":"Tera Shift"},
  "teraform-zero": {"name":"Teraform Zero"},
  "teravolt": {"name":"Teravolt","effect":"QUEBRA_GUARDA"},
  "thermal-exchange": {"name":"Thermal Exchange","effect":"REVIDE"},
  "thick-fat": {"name":"Thick Fat","effect":"PELAGEM","param":"do tipo Fogo ou Gelo"},
  "tinted-lens": {"name":"Tinted Lens","effect":"LENTE"},
  "torrent": {"name":"Torrent","effect":"FURIA_TIPO","param":"Água"},
  "tough-claws": {"name":"Tough Claws","effect":"MAESTRIA_GOLPE","param":"de contato"},
  "toxic-boost": {"name":"Toxic Boost","effect":"ADVERSIDADE"},
  "toxic-chain": {"name":"Toxic Chain","effect":"TOQUE","param":"Vitalidade"},
  "toxic-debris": {"name":"Toxic Debris","effect":"ESPINHOS"},
  "trace": {"name":"Trace"},
  "transistor": {"name":"Transistor","effect":"MAESTRIA_TIPO","param":"Elétrico"},
  "triage": {"name":"Triage","effect":"IMPULSO"},
  "truant": {"name":"Truant"},
  "turboblaze": {"name":"Turboblaze","effect":"QUEBRA_GUARDA"},
  "unaware": {"name":"Unaware","effect":"NEGAR_BUFF"},
  "unburden": {"name":"Unburden","effect":"IMPULSO"},
  "unnerve": {"name":"Unnerve","effect":"INTIMIDACAO","param":"Instinto"},
  "unseen-fist": {"name":"Unseen Fist","effect":"QUEBRA_GUARDA"},
  "vessel-of-ruin": {"name":"Vessel of Ruin","effect":"INTIMIDACAO","param":"Instinto"},
  "victory-star": {"name":"Victory Star","effect":"QUEBRA_GUARDA"},
  "vital-spirit": {"name":"Vital Spirit","effect":"CORPO_LIMPO"},
  "volt-absorb": {"name":"Volt Absorb","effect":"ABSORCAO","param":"Elétrico"},
  "wandering-spirit": {"name":"Wandering Spirit","effect":"REACAO","param":"Instinto"},
  "water-absorb": {"name":"Water Absorb","effect":"ABSORCAO","param":"Água"},
  "water-bubble": {"name":"Water Bubble","effect":"PELAGEM","param":"do tipo Fogo"},
  "water-compaction": {"name":"Water Compaction","effect":"PREPARO"},
  "water-veil": {"name":"Water Veil","effect":"CORPO_LIMPO"},
  "weak-armor": {"name":"Weak Armor","effect":"IMPULSO"},
  "well-baked-body": {"name":"Well-Baked Body","effect":"ABSORCAO","param":"Fogo"},
  "white-smoke": {"name":"White Smoke","effect":"CORPO_LIMPO"},
  "wimp-out": {"name":"Wimp Out","effect":"RETIRADA"},
  "wind-power": {"name":"Wind Power","effect":"REVIDE"},
  "wind-rider": {"name":"Wind Rider","effect":"ABSORCAO","param":"Voador"},
  "wonder-guard": {"name":"Wonder Guard","effect":"GUARDA_PERFEITA"},
  "wonder-skin": {"name":"Wonder Skin","effect":"EVASIVA"},
  "zen-mode": {"name":"Zen Mode"},
  "zero-to-hero": {"name":"Zero to Hero"},
};

// pokemonId -> [habilidades comuns, habilidade oculta]
export const SPECIES_ABILITIES: Record<number, [string[], string | null]> = {
  1: [["overgrow"],"chlorophyll"],
  2: [["overgrow"],"chlorophyll"],
  3: [["overgrow"],"chlorophyll"],
  4: [["blaze"],"solar-power"],
  5: [["blaze"],"solar-power"],
  6: [["blaze"],"solar-power"],
  7: [["torrent"],"rain-dish"],
  8: [["torrent"],"rain-dish"],
  9: [["torrent"],"rain-dish"],
  10: [["shield-dust"],"run-away"],
  11: [["shed-skin"],null],
  12: [["compound-eyes"],"tinted-lens"],
  13: [["shield-dust"],"run-away"],
  14: [["shed-skin"],null],
  15: [["swarm"],"sniper"],
  16: [["keen-eye","tangled-feet"],"big-pecks"],
  17: [["keen-eye","tangled-feet"],"big-pecks"],
  18: [["keen-eye","tangled-feet"],"big-pecks"],
  19: [["run-away","guts"],"hustle"],
  20: [["run-away","guts"],"hustle"],
  21: [["keen-eye"],"sniper"],
  22: [["keen-eye"],"sniper"],
  23: [["intimidate","shed-skin"],"unnerve"],
  24: [["intimidate","shed-skin"],"unnerve"],
  25: [["static"],"lightning-rod"],
  26: [["static"],"lightning-rod"],
  27: [["sand-veil"],"sand-rush"],
  28: [["sand-veil"],"sand-rush"],
  29: [["poison-point","rivalry"],"hustle"],
  30: [["poison-point","rivalry"],"hustle"],
  31: [["poison-point","rivalry"],"sheer-force"],
  32: [["poison-point","rivalry"],"hustle"],
  33: [["poison-point","rivalry"],"hustle"],
  34: [["poison-point","rivalry"],"sheer-force"],
  35: [["cute-charm","magic-guard"],"friend-guard"],
  36: [["cute-charm","magic-guard"],"unaware"],
  37: [["flash-fire"],"drought"],
  38: [["flash-fire"],"drought"],
  39: [["cute-charm","competitive"],"friend-guard"],
  40: [["cute-charm","competitive"],"frisk"],
  41: [["inner-focus"],"infiltrator"],
  42: [["inner-focus"],"infiltrator"],
  43: [["chlorophyll"],"run-away"],
  44: [["chlorophyll"],"stench"],
  45: [["chlorophyll"],"effect-spore"],
  46: [["effect-spore","dry-skin"],"damp"],
  47: [["effect-spore","dry-skin"],"damp"],
  48: [["compound-eyes","tinted-lens"],"run-away"],
  49: [["shield-dust","tinted-lens"],"wonder-skin"],
  50: [["sand-veil","arena-trap"],"sand-force"],
  51: [["sand-veil","arena-trap"],"sand-force"],
  52: [["pickup","technician"],"unnerve"],
  53: [["limber","technician"],"unnerve"],
  54: [["damp","cloud-nine"],"swift-swim"],
  55: [["damp","cloud-nine"],"swift-swim"],
  56: [["vital-spirit","anger-point"],"defiant"],
  57: [["vital-spirit","anger-point"],"defiant"],
  58: [["intimidate","flash-fire"],"justified"],
  59: [["intimidate","flash-fire"],"justified"],
  60: [["water-absorb","damp"],"swift-swim"],
  61: [["water-absorb","damp"],"swift-swim"],
  62: [["water-absorb","damp"],"swift-swim"],
  63: [["synchronize","inner-focus"],"magic-guard"],
  64: [["synchronize","inner-focus"],"magic-guard"],
  65: [["synchronize","inner-focus"],"magic-guard"],
  66: [["guts","no-guard"],"steadfast"],
  67: [["guts","no-guard"],"steadfast"],
  68: [["guts","no-guard"],"steadfast"],
  69: [["chlorophyll"],"gluttony"],
  70: [["chlorophyll"],"gluttony"],
  71: [["chlorophyll"],"gluttony"],
  72: [["clear-body","liquid-ooze"],"rain-dish"],
  73: [["clear-body","liquid-ooze"],"rain-dish"],
  74: [["rock-head","sturdy"],"sand-veil"],
  75: [["rock-head","sturdy"],"sand-veil"],
  76: [["rock-head","sturdy"],"sand-veil"],
  77: [["run-away","flash-fire"],"flame-body"],
  78: [["run-away","flash-fire"],"flame-body"],
  79: [["oblivious","own-tempo"],"regenerator"],
  80: [["oblivious","own-tempo"],"regenerator"],
  81: [["magnet-pull","sturdy"],"analytic"],
  82: [["magnet-pull","sturdy"],"analytic"],
  83: [["keen-eye","inner-focus"],"defiant"],
  84: [["run-away","early-bird"],"tangled-feet"],
  85: [["run-away","early-bird"],"tangled-feet"],
  86: [["thick-fat","hydration"],"ice-body"],
  87: [["thick-fat","hydration"],"ice-body"],
  88: [["stench","sticky-hold"],"poison-touch"],
  89: [["stench","sticky-hold"],"poison-touch"],
  90: [["shell-armor","skill-link"],"overcoat"],
  91: [["shell-armor","skill-link"],"overcoat"],
  92: [["levitate"],null],
  93: [["levitate"],null],
  94: [["cursed-body"],null],
  95: [["rock-head","sturdy"],"weak-armor"],
  96: [["insomnia","forewarn"],"inner-focus"],
  97: [["insomnia","forewarn"],"inner-focus"],
  98: [["hyper-cutter","shell-armor"],"sheer-force"],
  99: [["hyper-cutter","shell-armor"],"sheer-force"],
  100: [["soundproof","static"],"aftermath"],
  101: [["soundproof","static"],"aftermath"],
  102: [["chlorophyll"],"harvest"],
  103: [["chlorophyll"],"harvest"],
  104: [["rock-head","lightning-rod"],"battle-armor"],
  105: [["rock-head","lightning-rod"],"battle-armor"],
  106: [["limber","reckless"],"unburden"],
  107: [["keen-eye","iron-fist"],"inner-focus"],
  108: [["own-tempo","oblivious"],"cloud-nine"],
  109: [["levitate","neutralizing-gas"],"stench"],
  110: [["levitate","neutralizing-gas"],"stench"],
  111: [["lightning-rod","rock-head"],"reckless"],
  112: [["lightning-rod","rock-head"],"reckless"],
  113: [["natural-cure","serene-grace"],"healer"],
  114: [["chlorophyll","leaf-guard"],"regenerator"],
  115: [["early-bird","scrappy"],"inner-focus"],
  116: [["swift-swim","sniper"],"damp"],
  117: [["poison-point","sniper"],"damp"],
  118: [["swift-swim","water-veil"],"lightning-rod"],
  119: [["swift-swim","water-veil"],"lightning-rod"],
  120: [["illuminate","natural-cure"],"analytic"],
  121: [["illuminate","natural-cure"],"analytic"],
  122: [["soundproof","filter"],"technician"],
  123: [["swarm","technician"],"steadfast"],
  124: [["oblivious","forewarn"],"dry-skin"],
  125: [["static"],"vital-spirit"],
  126: [["flame-body"],"vital-spirit"],
  127: [["hyper-cutter","mold-breaker"],"moxie"],
  128: [["intimidate","anger-point"],"sheer-force"],
  129: [["swift-swim"],"rattled"],
  130: [["intimidate"],"moxie"],
  131: [["water-absorb","shell-armor"],"hydration"],
  132: [["limber"],"imposter"],
  133: [["run-away","adaptability"],"anticipation"],
  134: [["water-absorb"],"hydration"],
  135: [["volt-absorb"],"quick-feet"],
  136: [["flash-fire"],"guts"],
  137: [["trace","download"],"analytic"],
  138: [["swift-swim","shell-armor"],"weak-armor"],
  139: [["swift-swim","shell-armor"],"weak-armor"],
  140: [["swift-swim","battle-armor"],"weak-armor"],
  141: [["swift-swim","battle-armor"],"weak-armor"],
  142: [["rock-head","pressure"],"unnerve"],
  143: [["immunity","thick-fat"],"gluttony"],
  144: [["pressure"],"snow-cloak"],
  145: [["pressure"],"static"],
  146: [["pressure"],"flame-body"],
  147: [["shed-skin"],"marvel-scale"],
  148: [["shed-skin"],"marvel-scale"],
  149: [["inner-focus"],"multiscale"],
  150: [["pressure"],"unnerve"],
  151: [["synchronize"],null],
  152: [["overgrow"],"leaf-guard"],
  153: [["overgrow"],"leaf-guard"],
  154: [["overgrow"],"leaf-guard"],
  155: [["blaze"],"flash-fire"],
  156: [["blaze"],"flash-fire"],
  157: [["blaze"],"flash-fire"],
  158: [["torrent"],"sheer-force"],
  159: [["torrent"],"sheer-force"],
  160: [["torrent"],"sheer-force"],
  161: [["run-away","keen-eye"],"frisk"],
  162: [["run-away","keen-eye"],"frisk"],
  163: [["insomnia","keen-eye"],"tinted-lens"],
  164: [["insomnia","keen-eye"],"tinted-lens"],
  165: [["swarm","early-bird"],"rattled"],
  166: [["swarm","early-bird"],"iron-fist"],
  167: [["swarm","insomnia"],"sniper"],
  168: [["swarm","insomnia"],"sniper"],
  169: [["inner-focus"],"infiltrator"],
  170: [["volt-absorb","illuminate"],"water-absorb"],
  171: [["volt-absorb","illuminate"],"water-absorb"],
  172: [["static"],"lightning-rod"],
  173: [["cute-charm","magic-guard"],"friend-guard"],
  174: [["cute-charm","competitive"],"friend-guard"],
  175: [["hustle","serene-grace"],"super-luck"],
  176: [["hustle","serene-grace"],"super-luck"],
  177: [["synchronize","early-bird"],"magic-bounce"],
  178: [["synchronize","early-bird"],"magic-bounce"],
  179: [["static"],"plus"],
  180: [["static"],"plus"],
  181: [["static"],"plus"],
  182: [["chlorophyll"],"healer"],
  183: [["thick-fat","huge-power"],"sap-sipper"],
  184: [["thick-fat","huge-power"],"sap-sipper"],
  185: [["sturdy","rock-head"],"rattled"],
  186: [["water-absorb","damp"],"drizzle"],
  187: [["chlorophyll","leaf-guard"],"infiltrator"],
  188: [["chlorophyll","leaf-guard"],"infiltrator"],
  189: [["chlorophyll","leaf-guard"],"infiltrator"],
  190: [["run-away","pickup"],"skill-link"],
  191: [["chlorophyll","solar-power"],"early-bird"],
  192: [["chlorophyll","solar-power"],"early-bird"],
  193: [["speed-boost","compound-eyes"],"frisk"],
  194: [["damp","water-absorb"],"unaware"],
  195: [["damp","water-absorb"],"unaware"],
  196: [["synchronize"],"magic-bounce"],
  197: [["synchronize"],"inner-focus"],
  198: [["insomnia","super-luck"],"prankster"],
  199: [["oblivious","own-tempo"],"regenerator"],
  200: [["levitate"],null],
  201: [["levitate"],null],
  202: [["shadow-tag"],"telepathy"],
  203: [["inner-focus","early-bird"],"sap-sipper"],
  204: [["sturdy"],"overcoat"],
  205: [["sturdy"],"overcoat"],
  206: [["serene-grace","run-away"],"rattled"],
  207: [["hyper-cutter","sand-veil"],"immunity"],
  208: [["rock-head","sturdy"],"sheer-force"],
  209: [["intimidate","run-away"],"rattled"],
  210: [["intimidate","quick-feet"],"rattled"],
  211: [["poison-point","swift-swim"],"intimidate"],
  212: [["swarm","technician"],"light-metal"],
  213: [["sturdy","gluttony"],"contrary"],
  214: [["swarm","guts"],"moxie"],
  215: [["inner-focus","keen-eye"],"pickpocket"],
  216: [["pickup","quick-feet"],"honey-gather"],
  217: [["guts","quick-feet"],"unnerve"],
  218: [["magma-armor","flame-body"],"weak-armor"],
  219: [["magma-armor","flame-body"],"weak-armor"],
  220: [["oblivious","snow-cloak"],"thick-fat"],
  221: [["oblivious","snow-cloak"],"thick-fat"],
  222: [["hustle","natural-cure"],"regenerator"],
  223: [["hustle","sniper"],"moody"],
  224: [["suction-cups","sniper"],"moody"],
  225: [["vital-spirit","hustle"],"insomnia"],
  226: [["swift-swim","water-absorb"],"water-veil"],
  227: [["keen-eye","sturdy"],"weak-armor"],
  228: [["early-bird","flash-fire"],"unnerve"],
  229: [["early-bird","flash-fire"],"unnerve"],
  230: [["swift-swim","sniper"],"damp"],
  231: [["pickup"],"sand-veil"],
  232: [["sturdy"],"sand-veil"],
  233: [["trace","download"],"analytic"],
  234: [["intimidate","frisk"],"sap-sipper"],
  235: [["own-tempo","technician"],"moody"],
  236: [["guts","steadfast"],"vital-spirit"],
  237: [["intimidate","technician"],"steadfast"],
  238: [["oblivious","forewarn"],"hydration"],
  239: [["static"],"vital-spirit"],
  240: [["flame-body"],"vital-spirit"],
  241: [["thick-fat","scrappy"],"sap-sipper"],
  242: [["natural-cure","serene-grace"],"healer"],
  243: [["pressure"],"inner-focus"],
  244: [["pressure"],"inner-focus"],
  245: [["pressure"],"inner-focus"],
  246: [["guts"],"sand-veil"],
  247: [["shed-skin"],null],
  248: [["sand-stream"],"unnerve"],
  249: [["pressure"],"multiscale"],
  250: [["pressure"],"regenerator"],
  251: [["natural-cure"],null],
  252: [["overgrow"],"unburden"],
  253: [["overgrow"],"unburden"],
  254: [["overgrow"],"unburden"],
  255: [["blaze"],"speed-boost"],
  256: [["blaze"],"speed-boost"],
  257: [["blaze"],"speed-boost"],
  258: [["torrent"],"damp"],
  259: [["torrent"],"damp"],
  260: [["torrent"],"damp"],
  261: [["run-away","quick-feet"],"rattled"],
  262: [["intimidate","quick-feet"],"moxie"],
  263: [["pickup","gluttony"],"quick-feet"],
  264: [["pickup","gluttony"],"quick-feet"],
  265: [["shield-dust"],"run-away"],
  266: [["shed-skin"],null],
  267: [["swarm"],"rivalry"],
  268: [["shed-skin"],null],
  269: [["shield-dust"],"compound-eyes"],
  270: [["swift-swim","rain-dish"],"own-tempo"],
  271: [["swift-swim","rain-dish"],"own-tempo"],
  272: [["swift-swim","rain-dish"],"own-tempo"],
  273: [["chlorophyll","early-bird"],"pickpocket"],
  274: [["chlorophyll","early-bird"],"pickpocket"],
  275: [["chlorophyll","wind-rider"],"pickpocket"],
  276: [["guts"],"scrappy"],
  277: [["guts"],"scrappy"],
  278: [["keen-eye","hydration"],"rain-dish"],
  279: [["keen-eye","drizzle"],"rain-dish"],
  280: [["synchronize","trace"],"telepathy"],
  281: [["synchronize","trace"],"telepathy"],
  282: [["synchronize","trace"],"telepathy"],
  283: [["swift-swim"],"rain-dish"],
  284: [["intimidate"],"unnerve"],
  285: [["effect-spore","poison-heal"],"quick-feet"],
  286: [["effect-spore","poison-heal"],"technician"],
  287: [["truant"],null],
  288: [["vital-spirit"],null],
  289: [["truant"],null],
  290: [["compound-eyes"],"run-away"],
  291: [["speed-boost"],"infiltrator"],
  292: [["wonder-guard"],null],
  293: [["soundproof"],"rattled"],
  294: [["soundproof"],"scrappy"],
  295: [["soundproof"],"scrappy"],
  296: [["thick-fat","guts"],"sheer-force"],
  297: [["thick-fat","guts"],"sheer-force"],
  298: [["thick-fat","huge-power"],"sap-sipper"],
  299: [["sturdy","magnet-pull"],"sand-force"],
  300: [["cute-charm","normalize"],"wonder-skin"],
  301: [["cute-charm","normalize"],"wonder-skin"],
  302: [["keen-eye","stall"],"prankster"],
  303: [["hyper-cutter","intimidate"],"sheer-force"],
  304: [["sturdy","rock-head"],"heavy-metal"],
  305: [["sturdy","rock-head"],"heavy-metal"],
  306: [["sturdy","rock-head"],"heavy-metal"],
  307: [["pure-power"],"telepathy"],
  308: [["pure-power"],"telepathy"],
  309: [["static","lightning-rod"],"minus"],
  310: [["static","lightning-rod"],"minus"],
  311: [["plus"],"lightning-rod"],
  312: [["minus"],"volt-absorb"],
  313: [["illuminate","swarm"],"prankster"],
  314: [["oblivious","tinted-lens"],"prankster"],
  315: [["natural-cure","poison-point"],"leaf-guard"],
  316: [["liquid-ooze","sticky-hold"],"gluttony"],
  317: [["liquid-ooze","sticky-hold"],"gluttony"],
  318: [["rough-skin"],"speed-boost"],
  319: [["rough-skin"],"speed-boost"],
  320: [["water-veil","oblivious"],"pressure"],
  321: [["water-veil","oblivious"],"pressure"],
  322: [["oblivious","simple"],"own-tempo"],
  323: [["magma-armor","solid-rock"],"anger-point"],
  324: [["white-smoke","drought"],"shell-armor"],
  325: [["thick-fat","own-tempo"],"gluttony"],
  326: [["thick-fat","own-tempo"],"gluttony"],
  327: [["own-tempo","tangled-feet"],"contrary"],
  328: [["hyper-cutter","arena-trap"],"sheer-force"],
  329: [["levitate"],null],
  330: [["levitate"],null],
  331: [["sand-veil"],"water-absorb"],
  332: [["sand-veil"],"water-absorb"],
  333: [["natural-cure"],"cloud-nine"],
  334: [["natural-cure"],"cloud-nine"],
  335: [["immunity"],"toxic-boost"],
  336: [["shed-skin"],"infiltrator"],
  337: [["levitate"],null],
  338: [["levitate"],null],
  339: [["oblivious","anticipation"],"hydration"],
  340: [["oblivious","anticipation"],"hydration"],
  341: [["hyper-cutter","shell-armor"],"adaptability"],
  342: [["hyper-cutter","shell-armor"],"adaptability"],
  343: [["levitate"],null],
  344: [["levitate"],null],
  345: [["suction-cups"],"storm-drain"],
  346: [["suction-cups"],"storm-drain"],
  347: [["battle-armor"],"swift-swim"],
  348: [["battle-armor"],"swift-swim"],
  349: [["swift-swim","oblivious"],"adaptability"],
  350: [["marvel-scale","competitive"],"cute-charm"],
  351: [["forecast"],null],
  352: [["color-change"],"protean"],
  353: [["insomnia","frisk"],"cursed-body"],
  354: [["insomnia","frisk"],"cursed-body"],
  355: [["levitate"],"frisk"],
  356: [["pressure"],"frisk"],
  357: [["chlorophyll","solar-power"],"harvest"],
  358: [["levitate"],null],
  359: [["pressure","super-luck"],"justified"],
  360: [["shadow-tag"],"telepathy"],
  361: [["inner-focus","ice-body"],"moody"],
  362: [["inner-focus","ice-body"],"moody"],
  363: [["thick-fat","ice-body"],"oblivious"],
  364: [["thick-fat","ice-body"],"oblivious"],
  365: [["thick-fat","ice-body"],"oblivious"],
  366: [["shell-armor"],"rattled"],
  367: [["swift-swim"],"water-veil"],
  368: [["swift-swim"],"hydration"],
  369: [["swift-swim","rock-head"],"sturdy"],
  370: [["swift-swim"],"hydration"],
  371: [["rock-head"],"sheer-force"],
  372: [["rock-head"],"overcoat"],
  373: [["intimidate"],"moxie"],
  374: [["clear-body"],"light-metal"],
  375: [["clear-body"],"light-metal"],
  376: [["clear-body"],"light-metal"],
  377: [["clear-body"],"sturdy"],
  378: [["clear-body"],"ice-body"],
  379: [["clear-body"],"light-metal"],
  380: [["levitate"],null],
  381: [["levitate"],null],
  382: [["drizzle"],null],
  383: [["drought"],null],
  384: [["air-lock"],null],
  385: [["serene-grace"],null],
  386: [["pressure"],null],
  387: [["overgrow"],"shell-armor"],
  388: [["overgrow"],"shell-armor"],
  389: [["overgrow"],"shell-armor"],
  390: [["blaze"],"iron-fist"],
  391: [["blaze"],"iron-fist"],
  392: [["blaze"],"iron-fist"],
  393: [["torrent"],"competitive"],
  394: [["torrent"],"competitive"],
  395: [["torrent"],"competitive"],
  396: [["keen-eye"],"reckless"],
  397: [["intimidate"],"reckless"],
  398: [["intimidate"],"reckless"],
  399: [["simple","unaware"],"moody"],
  400: [["simple","unaware"],"moody"],
  401: [["shed-skin"],"run-away"],
  402: [["swarm"],"technician"],
  403: [["rivalry","intimidate"],"guts"],
  404: [["rivalry","intimidate"],"guts"],
  405: [["rivalry","intimidate"],"guts"],
  406: [["natural-cure","poison-point"],"leaf-guard"],
  407: [["natural-cure","poison-point"],"technician"],
  408: [["mold-breaker"],"sheer-force"],
  409: [["mold-breaker"],"sheer-force"],
  410: [["sturdy"],"soundproof"],
  411: [["sturdy"],"soundproof"],
  412: [["shed-skin"],"overcoat"],
  413: [["anticipation"],"overcoat"],
  414: [["swarm"],"tinted-lens"],
  415: [["honey-gather"],"hustle"],
  416: [["pressure"],"unnerve"],
  417: [["run-away","pickup"],"volt-absorb"],
  418: [["swift-swim"],"water-veil"],
  419: [["swift-swim"],"water-veil"],
  420: [["chlorophyll"],null],
  421: [["flower-gift"],null],
  422: [["sticky-hold","storm-drain"],"sand-force"],
  423: [["sticky-hold","storm-drain"],"sand-force"],
  424: [["technician","pickup"],"skill-link"],
  425: [["aftermath","unburden"],"flare-boost"],
  426: [["aftermath","unburden"],"flare-boost"],
  427: [["run-away","klutz"],"limber"],
  428: [["cute-charm","klutz"],"limber"],
  429: [["levitate"],null],
  430: [["insomnia","super-luck"],"moxie"],
  431: [["limber","own-tempo"],"keen-eye"],
  432: [["thick-fat","own-tempo"],"defiant"],
  433: [["levitate"],null],
  434: [["stench","aftermath"],"keen-eye"],
  435: [["stench","aftermath"],"keen-eye"],
  436: [["levitate","heatproof"],"heavy-metal"],
  437: [["levitate","heatproof"],"heavy-metal"],
  438: [["sturdy","rock-head"],"rattled"],
  439: [["soundproof","filter"],"technician"],
  440: [["natural-cure","serene-grace"],"friend-guard"],
  441: [["keen-eye","tangled-feet"],"big-pecks"],
  442: [["pressure"],"infiltrator"],
  443: [["sand-veil"],"rough-skin"],
  444: [["sand-veil"],"rough-skin"],
  445: [["sand-veil"],"rough-skin"],
  446: [["pickup","thick-fat"],"gluttony"],
  447: [["steadfast","inner-focus"],"prankster"],
  448: [["steadfast","inner-focus"],"justified"],
  449: [["sand-stream"],"sand-force"],
  450: [["sand-stream"],"sand-force"],
  451: [["battle-armor","sniper"],"keen-eye"],
  452: [["battle-armor","sniper"],"keen-eye"],
  453: [["anticipation","dry-skin"],"poison-touch"],
  454: [["anticipation","dry-skin"],"poison-touch"],
  455: [["levitate"],null],
  456: [["swift-swim","storm-drain"],"water-veil"],
  457: [["swift-swim","storm-drain"],"water-veil"],
  458: [["swift-swim","water-absorb"],"water-veil"],
  459: [["snow-warning"],"soundproof"],
  460: [["snow-warning"],"soundproof"],
  461: [["pressure"],"pickpocket"],
  462: [["magnet-pull","sturdy"],"analytic"],
  463: [["own-tempo","oblivious"],"cloud-nine"],
  464: [["lightning-rod","solid-rock"],"reckless"],
  465: [["chlorophyll","leaf-guard"],"regenerator"],
  466: [["motor-drive"],"vital-spirit"],
  467: [["flame-body"],"vital-spirit"],
  468: [["hustle","serene-grace"],"super-luck"],
  469: [["speed-boost","tinted-lens"],"frisk"],
  470: [["leaf-guard"],"chlorophyll"],
  471: [["snow-cloak"],"ice-body"],
  472: [["hyper-cutter","sand-veil"],"poison-heal"],
  473: [["oblivious","snow-cloak"],"thick-fat"],
  474: [["adaptability","download"],"analytic"],
  475: [["steadfast","sharpness"],"justified"],
  476: [["sturdy","magnet-pull"],"sand-force"],
  477: [["pressure"],"frisk"],
  478: [["snow-cloak"],"cursed-body"],
  479: [["levitate"],null],
  480: [["levitate"],null],
  481: [["levitate"],null],
  482: [["levitate"],null],
  483: [["pressure"],"telepathy"],
  484: [["pressure"],"telepathy"],
  485: [["flash-fire"],"flame-body"],
  486: [["slow-start"],null],
  487: [["pressure"],"telepathy"],
  488: [["levitate"],null],
  489: [["hydration"],null],
  490: [["hydration"],null],
  491: [["bad-dreams"],null],
  492: [["natural-cure"],null],
  493: [["multitype"],null],
  494: [["victory-star"],null],
  495: [["overgrow"],"contrary"],
  496: [["overgrow"],"contrary"],
  497: [["overgrow"],"contrary"],
  498: [["blaze"],"thick-fat"],
  499: [["blaze"],"thick-fat"],
  500: [["blaze"],"reckless"],
  501: [["torrent"],"shell-armor"],
  502: [["torrent"],"shell-armor"],
  503: [["torrent"],"shell-armor"],
  504: [["run-away","keen-eye"],"analytic"],
  505: [["illuminate","keen-eye"],"analytic"],
  506: [["vital-spirit","pickup"],"run-away"],
  507: [["intimidate","sand-rush"],"scrappy"],
  508: [["intimidate","sand-rush"],"scrappy"],
  509: [["limber","unburden"],"prankster"],
  510: [["limber","unburden"],"prankster"],
  511: [["gluttony"],"overgrow"],
  512: [["gluttony"],"overgrow"],
  513: [["gluttony"],"blaze"],
  514: [["gluttony"],"blaze"],
  515: [["gluttony"],"torrent"],
  516: [["gluttony"],"torrent"],
  517: [["forewarn","synchronize"],"telepathy"],
  518: [["forewarn","synchronize"],"telepathy"],
  519: [["big-pecks","super-luck"],"rivalry"],
  520: [["big-pecks","super-luck"],"rivalry"],
  521: [["big-pecks","super-luck"],"rivalry"],
  522: [["lightning-rod","motor-drive"],"sap-sipper"],
  523: [["lightning-rod","motor-drive"],"sap-sipper"],
  524: [["sturdy","weak-armor"],"sand-force"],
  525: [["sturdy","weak-armor"],"sand-force"],
  526: [["sturdy","sand-stream"],"sand-force"],
  527: [["unaware","klutz"],"simple"],
  528: [["unaware","klutz"],"simple"],
  529: [["sand-rush","sand-force"],"mold-breaker"],
  530: [["sand-rush","sand-force"],"mold-breaker"],
  531: [["healer","regenerator"],"klutz"],
  532: [["guts","sheer-force"],"iron-fist"],
  533: [["guts","sheer-force"],"iron-fist"],
  534: [["guts","sheer-force"],"iron-fist"],
  535: [["swift-swim","hydration"],"water-absorb"],
  536: [["swift-swim","hydration"],"water-absorb"],
  537: [["swift-swim","poison-touch"],"water-absorb"],
  538: [["guts","inner-focus"],"mold-breaker"],
  539: [["sturdy","inner-focus"],"mold-breaker"],
  540: [["swarm","chlorophyll"],"overcoat"],
  541: [["leaf-guard","chlorophyll"],"overcoat"],
  542: [["swarm","chlorophyll"],"overcoat"],
  543: [["poison-point","swarm"],"speed-boost"],
  544: [["poison-point","swarm"],"speed-boost"],
  545: [["poison-point","swarm"],"speed-boost"],
  546: [["prankster","infiltrator"],"chlorophyll"],
  547: [["prankster","infiltrator"],"chlorophyll"],
  548: [["chlorophyll","own-tempo"],"leaf-guard"],
  549: [["chlorophyll","own-tempo"],"leaf-guard"],
  550: [["reckless","adaptability"],"mold-breaker"],
  551: [["intimidate","moxie"],"anger-point"],
  552: [["intimidate","moxie"],"anger-point"],
  553: [["intimidate","moxie"],"anger-point"],
  554: [["hustle"],"inner-focus"],
  555: [["sheer-force"],"zen-mode"],
  556: [["water-absorb","chlorophyll"],"storm-drain"],
  557: [["sturdy","shell-armor"],"weak-armor"],
  558: [["sturdy","shell-armor"],"weak-armor"],
  559: [["shed-skin","moxie"],"intimidate"],
  560: [["shed-skin","moxie"],"intimidate"],
  561: [["wonder-skin","magic-guard"],"tinted-lens"],
  562: [["mummy"],null],
  563: [["mummy"],null],
  564: [["solid-rock","sturdy"],"swift-swim"],
  565: [["solid-rock","sturdy"],"swift-swim"],
  566: [["defeatist"],null],
  567: [["defeatist"],null],
  568: [["stench","sticky-hold"],"aftermath"],
  569: [["stench","weak-armor"],"aftermath"],
  570: [["illusion"],null],
  571: [["illusion"],null],
  572: [["cute-charm","technician"],"skill-link"],
  573: [["cute-charm","technician"],"skill-link"],
  574: [["frisk","competitive"],"shadow-tag"],
  575: [["frisk","competitive"],"shadow-tag"],
  576: [["frisk","competitive"],"shadow-tag"],
  577: [["overcoat","magic-guard"],"regenerator"],
  578: [["overcoat","magic-guard"],"regenerator"],
  579: [["overcoat","magic-guard"],"regenerator"],
  580: [["keen-eye","big-pecks"],"hydration"],
  581: [["keen-eye","big-pecks"],"hydration"],
  582: [["ice-body","snow-cloak"],"weak-armor"],
  583: [["ice-body","snow-cloak"],"weak-armor"],
  584: [["ice-body","snow-warning"],"weak-armor"],
  585: [["chlorophyll","sap-sipper"],"serene-grace"],
  586: [["chlorophyll","sap-sipper"],"serene-grace"],
  587: [["static"],"motor-drive"],
  588: [["swarm","shed-skin"],"no-guard"],
  589: [["swarm","shell-armor"],"overcoat"],
  590: [["effect-spore"],"regenerator"],
  591: [["effect-spore"],"regenerator"],
  592: [["water-absorb","cursed-body"],"damp"],
  593: [["water-absorb","cursed-body"],"damp"],
  594: [["healer","hydration"],"regenerator"],
  595: [["compound-eyes","unnerve"],"swarm"],
  596: [["compound-eyes","unnerve"],"swarm"],
  597: [["iron-barbs"],null],
  598: [["iron-barbs"],"anticipation"],
  599: [["plus","minus"],"clear-body"],
  600: [["plus","minus"],"clear-body"],
  601: [["plus","minus"],"clear-body"],
  602: [["levitate"],null],
  603: [["levitate"],null],
  604: [["levitate"],null],
  605: [["telepathy","synchronize"],"analytic"],
  606: [["telepathy","synchronize"],"analytic"],
  607: [["flash-fire","flame-body"],"infiltrator"],
  608: [["flash-fire","flame-body"],"infiltrator"],
  609: [["flash-fire","flame-body"],"infiltrator"],
  610: [["rivalry","mold-breaker"],"unnerve"],
  611: [["rivalry","mold-breaker"],"unnerve"],
  612: [["rivalry","mold-breaker"],"unnerve"],
  613: [["snow-cloak","slush-rush"],"rattled"],
  614: [["snow-cloak","slush-rush"],"swift-swim"],
  615: [["levitate"],null],
  616: [["hydration","shell-armor"],"overcoat"],
  617: [["hydration","sticky-hold"],"unburden"],
  618: [["static","limber"],"sand-veil"],
  619: [["inner-focus","regenerator"],"reckless"],
  620: [["inner-focus","regenerator"],"reckless"],
  621: [["rough-skin","sheer-force"],"mold-breaker"],
  622: [["iron-fist","klutz"],"no-guard"],
  623: [["iron-fist","klutz"],"no-guard"],
  624: [["defiant","inner-focus"],"pressure"],
  625: [["defiant","inner-focus"],"pressure"],
  626: [["reckless","sap-sipper"],"soundproof"],
  627: [["keen-eye","sheer-force"],"hustle"],
  628: [["keen-eye","sheer-force"],"defiant"],
  629: [["big-pecks","overcoat"],"weak-armor"],
  630: [["big-pecks","overcoat"],"weak-armor"],
  631: [["gluttony","flash-fire"],"white-smoke"],
  632: [["swarm","hustle"],"truant"],
  633: [["hustle"],null],
  634: [["hustle"],null],
  635: [["levitate"],null],
  636: [["flame-body"],"swarm"],
  637: [["flame-body"],"swarm"],
  638: [["justified"],null],
  639: [["justified"],null],
  640: [["justified"],null],
  641: [["prankster"],"defiant"],
  642: [["prankster"],"defiant"],
  643: [["turboblaze"],null],
  644: [["teravolt"],null],
  645: [["sand-force"],"sheer-force"],
  646: [["pressure"],null],
  647: [["justified"],null],
  648: [["serene-grace"],null],
  649: [["download"],null],
  650: [["overgrow"],"bulletproof"],
  651: [["overgrow"],"bulletproof"],
  652: [["overgrow"],"bulletproof"],
  653: [["blaze"],"magician"],
  654: [["blaze"],"magician"],
  655: [["blaze"],"magician"],
  656: [["torrent"],"protean"],
  657: [["torrent"],"protean"],
  658: [["torrent"],"protean"],
  659: [["pickup","cheek-pouch"],"huge-power"],
  660: [["pickup","cheek-pouch"],"huge-power"],
  661: [["big-pecks"],"gale-wings"],
  662: [["flame-body"],"gale-wings"],
  663: [["flame-body"],"gale-wings"],
  664: [["shield-dust","compound-eyes"],"friend-guard"],
  665: [["shed-skin"],"friend-guard"],
  666: [["shield-dust","compound-eyes"],"friend-guard"],
  667: [["rivalry","unnerve"],"moxie"],
  668: [["rivalry","unnerve"],"moxie"],
  669: [["flower-veil"],"symbiosis"],
  670: [["flower-veil"],"symbiosis"],
  671: [["flower-veil"],"symbiosis"],
  672: [["sap-sipper"],"grass-pelt"],
  673: [["sap-sipper"],"grass-pelt"],
  674: [["iron-fist","mold-breaker"],"scrappy"],
  675: [["iron-fist","mold-breaker"],"scrappy"],
  676: [["fur-coat"],null],
  677: [["keen-eye","infiltrator"],"own-tempo"],
  678: [["keen-eye","infiltrator"],"prankster"],
  679: [["no-guard"],null],
  680: [["no-guard"],null],
  681: [["stance-change"],null],
  682: [["healer"],"aroma-veil"],
  683: [["healer"],"aroma-veil"],
  684: [["sweet-veil"],"unburden"],
  685: [["sweet-veil"],"unburden"],
  686: [["contrary","suction-cups"],"infiltrator"],
  687: [["contrary","suction-cups"],"infiltrator"],
  688: [["tough-claws","sniper"],"pickpocket"],
  689: [["tough-claws","sniper"],"pickpocket"],
  690: [["poison-point","poison-touch"],"adaptability"],
  691: [["poison-point","poison-touch"],"adaptability"],
  692: [["mega-launcher"],null],
  693: [["mega-launcher"],null],
  694: [["dry-skin","sand-veil"],"solar-power"],
  695: [["dry-skin","sand-veil"],"solar-power"],
  696: [["strong-jaw"],"sturdy"],
  697: [["strong-jaw"],"rock-head"],
  698: [["refrigerate"],"snow-warning"],
  699: [["refrigerate"],"snow-warning"],
  700: [["cute-charm"],"pixilate"],
  701: [["limber","unburden"],"mold-breaker"],
  702: [["cheek-pouch","pickup"],"plus"],
  703: [["clear-body"],"sturdy"],
  704: [["sap-sipper","hydration"],"gooey"],
  705: [["sap-sipper","hydration"],"gooey"],
  706: [["sap-sipper","hydration"],"gooey"],
  707: [["prankster"],"magician"],
  708: [["natural-cure","frisk"],"harvest"],
  709: [["natural-cure","frisk"],"harvest"],
  710: [["pickup","frisk"],"insomnia"],
  711: [["pickup","frisk"],"insomnia"],
  712: [["own-tempo","ice-body"],"sturdy"],
  713: [["own-tempo","ice-body"],"sturdy"],
  714: [["frisk","infiltrator"],"telepathy"],
  715: [["frisk","infiltrator"],"telepathy"],
  716: [["fairy-aura"],null],
  717: [["dark-aura"],null],
  718: [["aura-break"],null],
  719: [["clear-body"],null],
  720: [["magician"],null],
  721: [["water-absorb"],null],
  722: [["overgrow"],"long-reach"],
  723: [["overgrow"],"long-reach"],
  724: [["overgrow"],"long-reach"],
  725: [["blaze"],"intimidate"],
  726: [["blaze"],"intimidate"],
  727: [["blaze"],"intimidate"],
  728: [["torrent"],"liquid-voice"],
  729: [["torrent"],"liquid-voice"],
  730: [["torrent"],"liquid-voice"],
  731: [["keen-eye","skill-link"],"pickup"],
  732: [["keen-eye","skill-link"],"pickup"],
  733: [["keen-eye","skill-link"],"sheer-force"],
  734: [["stakeout","strong-jaw"],"adaptability"],
  735: [["stakeout","strong-jaw"],"adaptability"],
  736: [["swarm"],null],
  737: [["battery"],null],
  738: [["levitate"],null],
  739: [["hyper-cutter","iron-fist"],"anger-point"],
  740: [["hyper-cutter","iron-fist"],"anger-point"],
  741: [["dancer"],null],
  742: [["honey-gather","shield-dust"],"sweet-veil"],
  743: [["honey-gather","shield-dust"],"sweet-veil"],
  744: [["keen-eye","vital-spirit"],"steadfast"],
  745: [["keen-eye","sand-rush"],"steadfast"],
  746: [["schooling"],null],
  747: [["merciless","limber"],"regenerator"],
  748: [["merciless","limber"],"regenerator"],
  749: [["own-tempo","stamina"],"inner-focus"],
  750: [["own-tempo","stamina"],"inner-focus"],
  751: [["water-bubble"],"water-absorb"],
  752: [["water-bubble"],"water-absorb"],
  753: [["leaf-guard"],"contrary"],
  754: [["leaf-guard"],"contrary"],
  755: [["illuminate","effect-spore"],"rain-dish"],
  756: [["illuminate","effect-spore"],"rain-dish"],
  757: [["corrosion"],"oblivious"],
  758: [["corrosion"],"oblivious"],
  759: [["fluffy","klutz"],"cute-charm"],
  760: [["fluffy","klutz"],"unnerve"],
  761: [["leaf-guard","oblivious"],"sweet-veil"],
  762: [["leaf-guard","oblivious"],"sweet-veil"],
  763: [["leaf-guard","queenly-majesty"],"sweet-veil"],
  764: [["flower-veil","triage"],"natural-cure"],
  765: [["inner-focus","telepathy"],"symbiosis"],
  766: [["receiver"],"defiant"],
  767: [["wimp-out"],null],
  768: [["emergency-exit"],null],
  769: [["water-compaction"],"sand-veil"],
  770: [["water-compaction"],"sand-veil"],
  771: [["innards-out"],"unaware"],
  772: [["battle-armor"],null],
  773: [["rks-system"],null],
  774: [["shields-down"],null],
  775: [["comatose"],null],
  776: [["shell-armor"],null],
  777: [["iron-barbs","lightning-rod"],"sturdy"],
  778: [["disguise"],null],
  779: [["dazzling","strong-jaw"],"wonder-skin"],
  780: [["berserk","sap-sipper"],"cloud-nine"],
  781: [["steelworker"],null],
  782: [["bulletproof","soundproof"],"overcoat"],
  783: [["bulletproof","soundproof"],"overcoat"],
  784: [["bulletproof","soundproof"],"overcoat"],
  785: [["electric-surge"],"telepathy"],
  786: [["psychic-surge"],"telepathy"],
  787: [["grassy-surge"],"telepathy"],
  788: [["misty-surge"],"telepathy"],
  789: [["unaware"],null],
  790: [["sturdy"],null],
  791: [["full-metal-body"],null],
  792: [["shadow-shield"],null],
  793: [["beast-boost"],null],
  794: [["beast-boost"],null],
  795: [["beast-boost"],null],
  796: [["beast-boost"],null],
  797: [["beast-boost"],null],
  798: [["beast-boost"],null],
  799: [["beast-boost"],null],
  800: [["prism-armor"],null],
  801: [["soul-heart"],null],
  802: [["technician"],null],
  803: [["beast-boost"],null],
  804: [["beast-boost"],null],
  805: [["beast-boost"],null],
  806: [["beast-boost"],null],
  807: [["volt-absorb"],null],
  808: [["magnet-pull"],null],
  809: [["iron-fist"],null],
  810: [["overgrow"],"grassy-surge"],
  811: [["overgrow"],"grassy-surge"],
  812: [["overgrow"],"grassy-surge"],
  813: [["blaze"],"libero"],
  814: [["blaze"],"libero"],
  815: [["blaze"],"libero"],
  816: [["torrent"],"sniper"],
  817: [["torrent"],"sniper"],
  818: [["torrent"],"sniper"],
  819: [["cheek-pouch"],"gluttony"],
  820: [["cheek-pouch"],"gluttony"],
  821: [["keen-eye","unnerve"],"big-pecks"],
  822: [["keen-eye","unnerve"],"big-pecks"],
  823: [["pressure","unnerve"],"mirror-armor"],
  824: [["swarm","compound-eyes"],"telepathy"],
  825: [["swarm","compound-eyes"],"telepathy"],
  826: [["swarm","frisk"],"telepathy"],
  827: [["run-away","unburden"],"stakeout"],
  828: [["run-away","unburden"],"stakeout"],
  829: [["cotton-down","regenerator"],"effect-spore"],
  830: [["cotton-down","regenerator"],"effect-spore"],
  831: [["fluffy","run-away"],"bulletproof"],
  832: [["fluffy","steadfast"],"bulletproof"],
  833: [["strong-jaw","shell-armor"],"swift-swim"],
  834: [["strong-jaw","shell-armor"],"swift-swim"],
  835: [["ball-fetch"],"rattled"],
  836: [["strong-jaw"],"competitive"],
  837: [["steam-engine","heatproof"],"flash-fire"],
  838: [["steam-engine","flame-body"],"flash-fire"],
  839: [["steam-engine","flame-body"],"flash-fire"],
  840: [["ripen","gluttony"],"bulletproof"],
  841: [["ripen","gluttony"],"hustle"],
  842: [["ripen","gluttony"],"thick-fat"],
  843: [["sand-spit","shed-skin"],"sand-veil"],
  844: [["sand-spit","shed-skin"],"sand-veil"],
  845: [["gulp-missile"],null],
  846: [["swift-swim"],"propeller-tail"],
  847: [["swift-swim"],"propeller-tail"],
  848: [["rattled","static"],"klutz"],
  849: [["punk-rock","plus"],"technician"],
  850: [["flash-fire","white-smoke"],"flame-body"],
  851: [["flash-fire","white-smoke"],"flame-body"],
  852: [["limber"],"technician"],
  853: [["limber"],"technician"],
  854: [["weak-armor"],"cursed-body"],
  855: [["weak-armor"],"cursed-body"],
  856: [["healer","anticipation"],"magic-bounce"],
  857: [["healer","anticipation"],"magic-bounce"],
  858: [["healer","anticipation"],"magic-bounce"],
  859: [["prankster","frisk"],"pickpocket"],
  860: [["prankster","frisk"],"pickpocket"],
  861: [["prankster","frisk"],"pickpocket"],
  862: [["reckless","guts"],"defiant"],
  863: [["battle-armor","tough-claws"],"steely-spirit"],
  864: [["weak-armor"],"perish-body"],
  865: [["steadfast"],"scrappy"],
  866: [["tangled-feet","screen-cleaner"],"ice-body"],
  867: [["wandering-spirit"],null],
  868: [["sweet-veil"],"aroma-veil"],
  869: [["sweet-veil"],"aroma-veil"],
  870: [["battle-armor"],"defiant"],
  871: [["lightning-rod"],"electric-surge"],
  872: [["shield-dust"],"ice-scales"],
  873: [["shield-dust"],"ice-scales"],
  874: [["power-spot"],null],
  875: [["ice-face"],null],
  876: [["inner-focus","synchronize"],"psychic-surge"],
  877: [["hunger-switch"],null],
  878: [["sheer-force"],"heavy-metal"],
  879: [["sheer-force"],"heavy-metal"],
  880: [["volt-absorb","hustle"],"sand-rush"],
  881: [["volt-absorb","static"],"slush-rush"],
  882: [["water-absorb","strong-jaw"],"sand-rush"],
  883: [["water-absorb","ice-body"],"slush-rush"],
  884: [["light-metal","heavy-metal"],"stalwart"],
  885: [["clear-body","infiltrator"],"cursed-body"],
  886: [["clear-body","infiltrator"],"cursed-body"],
  887: [["clear-body","infiltrator"],"cursed-body"],
  888: [["intrepid-sword"],null],
  889: [["dauntless-shield"],null],
  890: [["pressure"],null],
  891: [["inner-focus"],null],
  892: [["unseen-fist"],null],
  893: [["leaf-guard"],null],
  894: [["transistor"],null],
  895: [["dragons-maw"],null],
  896: [["chilling-neigh"],null],
  897: [["grim-neigh"],null],
  898: [["unnerve"],null],
  899: [["intimidate","frisk"],"sap-sipper"],
  900: [["swarm","sheer-force"],"sharpness"],
  901: [["guts","bulletproof"],"unnerve"],
  902: [["swift-swim","adaptability"],"mold-breaker"],
  903: [["pressure","unburden"],"poison-touch"],
  904: [["poison-point","swift-swim"],"intimidate"],
  905: [["cute-charm"],"contrary"],
  906: [["overgrow"],"protean"],
  907: [["overgrow"],"protean"],
  908: [["overgrow"],"protean"],
  909: [["blaze"],"unaware"],
  910: [["blaze"],"unaware"],
  911: [["blaze"],"unaware"],
  912: [["torrent"],"moxie"],
  913: [["torrent"],"moxie"],
  914: [["torrent"],"moxie"],
  915: [["aroma-veil","gluttony"],"thick-fat"],
  916: [["lingering-aroma","gluttony"],"thick-fat"],
  917: [["insomnia"],"stakeout"],
  918: [["insomnia"],"stakeout"],
  919: [["swarm"],"tinted-lens"],
  920: [["swarm"],"tinted-lens"],
  921: [["static","natural-cure"],"iron-fist"],
  922: [["volt-absorb","natural-cure"],"iron-fist"],
  923: [["volt-absorb","natural-cure"],"iron-fist"],
  924: [["run-away","pickup"],"own-tempo"],
  925: [["friend-guard","cheek-pouch"],"technician"],
  926: [["own-tempo"],"klutz"],
  927: [["well-baked-body"],"aroma-veil"],
  928: [["early-bird"],"harvest"],
  929: [["early-bird"],"harvest"],
  930: [["seed-sower"],"harvest"],
  931: [["intimidate","hustle"],"guts"],
  932: [["purifying-salt","sturdy"],"clear-body"],
  933: [["purifying-salt","sturdy"],"clear-body"],
  934: [["purifying-salt","sturdy"],"clear-body"],
  935: [["flash-fire"],"flame-body"],
  936: [["flash-fire"],"weak-armor"],
  937: [["flash-fire"],"weak-armor"],
  938: [["own-tempo","static"],"damp"],
  939: [["electromorphosis","static"],"damp"],
  940: [["wind-power","volt-absorb"],"competitive"],
  941: [["wind-power","volt-absorb"],"competitive"],
  942: [["intimidate","run-away"],"stakeout"],
  943: [["intimidate","guard-dog"],"stakeout"],
  944: [["unburden","pickpocket"],"prankster"],
  945: [["unburden","poison-touch"],"prankster"],
  946: [["wind-rider"],"infiltrator"],
  947: [["wind-rider"],"infiltrator"],
  948: [["mycelium-might"],null],
  949: [["mycelium-might"],null],
  950: [["anger-shell","shell-armor"],"regenerator"],
  951: [["chlorophyll","insomnia"],"klutz"],
  952: [["chlorophyll","insomnia"],"moody"],
  953: [["compound-eyes"],"shed-skin"],
  954: [["synchronize"],"telepathy"],
  955: [["anticipation","frisk"],"speed-boost"],
  956: [["opportunist","frisk"],"speed-boost"],
  957: [["mold-breaker","own-tempo"],"pickpocket"],
  958: [["mold-breaker","own-tempo"],"pickpocket"],
  959: [["mold-breaker","own-tempo"],"pickpocket"],
  960: [["gooey","rattled"],"sand-veil"],
  961: [["gooey","rattled"],"sand-veil"],
  962: [["big-pecks","keen-eye"],"rocky-payload"],
  963: [["water-veil"],null],
  964: [["zero-to-hero"],null],
  965: [["overcoat"],"slow-start"],
  966: [["overcoat"],"filter"],
  967: [["shed-skin"],"regenerator"],
  968: [["earth-eater"],"sand-veil"],
  969: [["toxic-debris"],"corrosion"],
  970: [["toxic-debris"],"corrosion"],
  971: [["pickup"],"fluffy"],
  972: [["sand-rush"],"fluffy"],
  973: [["scrappy","tangled-feet"],"costar"],
  974: [["thick-fat","snow-cloak"],"sheer-force"],
  975: [["thick-fat","slush-rush"],"sheer-force"],
  976: [["mold-breaker"],"sharpness"],
  977: [["unaware","oblivious"],"water-veil"],
  978: [["commander"],"storm-drain"],
  979: [["vital-spirit","inner-focus"],"defiant"],
  980: [["poison-point","water-absorb"],"unaware"],
  981: [["cud-chew","armor-tail"],"sap-sipper"],
  982: [["serene-grace","run-away"],"rattled"],
  983: [["defiant","supreme-overlord"],"pressure"],
  984: [["protosynthesis"],null],
  985: [["protosynthesis"],null],
  986: [["protosynthesis"],null],
  987: [["protosynthesis"],null],
  988: [["protosynthesis"],null],
  989: [["protosynthesis"],null],
  990: [["quark-drive"],null],
  991: [["quark-drive"],null],
  992: [["quark-drive"],null],
  993: [["quark-drive"],null],
  994: [["quark-drive"],null],
  995: [["quark-drive"],null],
  996: [["thermal-exchange"],"ice-body"],
  997: [["thermal-exchange"],"ice-body"],
  998: [["thermal-exchange"],"ice-body"],
  999: [["rattled"],null],
  1000: [["good-as-gold"],null],
  1001: [["tablets-of-ruin"],null],
  1002: [["sword-of-ruin"],null],
  1003: [["vessel-of-ruin"],null],
  1004: [["beads-of-ruin"],null],
  1005: [["protosynthesis"],null],
  1006: [["quark-drive"],null],
  1007: [["orichalcum-pulse"],null],
  1008: [["hadron-engine"],null],
  1009: [["protosynthesis"],null],
  1010: [["quark-drive"],null],
  1011: [["supersweet-syrup","gluttony"],"sticky-hold"],
  1012: [["hospitality"],"heatproof"],
  1013: [["hospitality"],"heatproof"],
  1014: [["toxic-chain"],"guard-dog"],
  1015: [["toxic-chain"],"frisk"],
  1016: [["toxic-chain"],"technician"],
  1017: [["defiant"],null],
  1018: [["stamina","sturdy"],"stalwart"],
  1019: [["supersweet-syrup","regenerator"],"sticky-hold"],
  1020: [["protosynthesis"],null],
  1021: [["protosynthesis"],null],
  1022: [["quark-drive"],null],
  1023: [["quark-drive"],null],
  1024: [["tera-shift"],null],
  1025: [["poison-puppeteer"],null],
  10001: [["pressure"],null],
  10002: [["pressure"],null],
  10003: [["pressure"],null],
  10014: [["forecast"],null],
  10015: [["forecast"],null],
  10016: [["rock-head","adaptability"],"mold-breaker"],
  10017: [["sheer-force"],"zen-mode"],
  10018: [["serene-grace"],null],
  10019: [["regenerator"],null],
  10020: [["volt-absorb"],null],
  10021: [["intimidate"],null],
  10022: [["teravolt"],null],
  10023: [["turboblaze"],null],
  10024: [["justified"],null],
  10025: [["keen-eye","infiltrator"],"competitive"],
  10026: [["stance-change"],null],
  10027: [["pickup","frisk"],"insomnia"],
  10028: [["pickup","frisk"],"insomnia"],
  10029: [["pickup","frisk"],"insomnia"],
  10030: [["pickup","frisk"],"insomnia"],
  10031: [["pickup","frisk"],"insomnia"],
  10032: [["pickup","frisk"],"insomnia"],
  10033: [["thick-fat"],null],
  10034: [["tough-claws"],null],
  10035: [["drought"],null],
  10036: [["mega-launcher"],null],
  10037: [["trace"],null],
  10038: [["shadow-tag"],null],
  10039: [["parental-bond"],null],
  10040: [["aerilate"],null],
  10041: [["mold-breaker"],null],
  10042: [["tough-claws"],null],
  10043: [["steadfast"],null],
  10044: [["insomnia"],null],
  10045: [["mold-breaker"],null],
  10046: [["technician"],null],
  10047: [["skill-link"],null],
  10048: [["solar-power"],null],
  10049: [["sand-stream"],null],
  10050: [["speed-boost"],null],
  10051: [["pixilate"],null],
  10052: [["huge-power"],null],
  10053: [["filter"],null],
  10054: [["pure-power"],null],
  10055: [["intimidate"],null],
  10056: [["prankster"],null],
  10057: [["magic-bounce"],null],
  10058: [["sand-force"],null],
  10059: [["adaptability"],null],
  10060: [["snow-warning"],null],
  10061: [["flower-veil"],"symbiosis"],
  10062: [["levitate"],null],
  10063: [["levitate"],null],
  10064: [["swift-swim"],null],
  10065: [["lightning-rod"],null],
  10066: [["magic-bounce"],null],
  10067: [["pixilate"],null],
  10068: [["inner-focus"],null],
  10069: [["healer"],null],
  10070: [["strong-jaw"],null],
  10071: [["shell-armor"],null],
  10072: [["sand-force"],null],
  10073: [["no-guard"],null],
  10074: [["refrigerate"],null],
  10075: [["magic-bounce"],null],
  10076: [["tough-claws"],null],
  10077: [["primordial-sea"],null],
  10078: [["desolate-land"],null],
  10079: [["delta-stream"],null],
  10080: [["static"],"lightning-rod"],
  10081: [["static"],"lightning-rod"],
  10082: [["static"],"lightning-rod"],
  10083: [["static"],"lightning-rod"],
  10084: [["static"],"lightning-rod"],
  10085: [["static"],"lightning-rod"],
  10086: [["magician"],null],
  10087: [["sheer-force"],null],
  10088: [["scrappy"],null],
  10089: [["aerilate"],null],
  10090: [["adaptability"],null],
  10093: [["gluttony","hustle"],"thick-fat"],
  10094: [["static"],"lightning-rod"],
  10095: [["static"],"lightning-rod"],
  10096: [["static"],"lightning-rod"],
  10097: [["static"],"lightning-rod"],
  10098: [["static"],"lightning-rod"],
  10099: [["static"],"lightning-rod"],
  10116: [["battle-bond"],null],
  10117: [["battle-bond"],null],
  10118: [["power-construct"],null],
  10119: [["power-construct"],null],
  10120: [["power-construct"],null],
  10121: [["stakeout","strong-jaw"],"adaptability"],
  10122: [["levitate"],null],
  10123: [["dancer"],null],
  10124: [["dancer"],null],
  10125: [["dancer"],null],
  10126: [["keen-eye","vital-spirit"],"no-guard"],
  10127: [["schooling"],null],
  10128: [["leaf-guard"],"contrary"],
  10129: [["corrosion"],"oblivious"],
  10130: [["shields-down"],null],
  10131: [["shields-down"],null],
  10132: [["shields-down"],null],
  10133: [["shields-down"],null],
  10134: [["shields-down"],null],
  10135: [["shields-down"],null],
  10136: [["shields-down"],null],
  10137: [["shields-down"],null],
  10138: [["shields-down"],null],
  10139: [["shields-down"],null],
  10140: [["shields-down"],null],
  10141: [["shields-down"],null],
  10142: [["shields-down"],null],
  10143: [["disguise"],null],
  10144: [["disguise"],null],
  10145: [["disguise"],null],
  10146: [["bulletproof","soundproof"],"overcoat"],
  10147: [["soul-heart"],null],
  10148: [["static"],"lightning-rod"],
  10149: [["cursed-body","lightning-rod"],"rock-head"],
  10150: [["honey-gather","shield-dust"],"sweet-veil"],
  10151: [["own-tempo"],null],
  10153: [["water-bubble"],"water-absorb"],
  10154: [["iron-barbs","lightning-rod"],"sturdy"],
  10156: [["prism-armor"],null],
  10157: [["neuroforce"],null],
  10177: [["gorilla-tactics"],"zen-mode"],
  10178: [["gorilla-tactics"],"zen-mode"],
  10179: [["wandering-spirit"],null],
  10180: [["mimicry"],null],
  10181: [["aura-break"],null],
  10182: [["gulp-missile"],null],
  10183: [["gulp-missile"],null],
  10185: [["ice-face"],null],
  10186: [["own-tempo","synchronize"],"psychic-surge"],
  10187: [["hunger-switch"],null],
  10188: [["intrepid-sword"],null],
  10189: [["dauntless-shield"],null],
  10190: [["pressure"],null],
  10191: [["unseen-fist"],null],
  10192: [["leaf-guard"],null],
  10193: [["as-one-spectrier"],null],
  10194: [["as-one-spectrier"],null],
  10195: [["overgrow"],"chlorophyll"],
  10196: [["blaze"],"solar-power"],
  10197: [["torrent"],"rain-dish"],
  10198: [["compound-eyes"],"tinted-lens"],
  10199: [["static"],"lightning-rod"],
  10200: [["pickup","technician"],"unnerve"],
  10201: [["guts","no-guard"],"steadfast"],
  10202: [["cursed-body"],null],
  10203: [["hyper-cutter","shell-armor"],"sheer-force"],
  10204: [["water-absorb","shell-armor"],"hydration"],
  10205: [["run-away","adaptability"],"anticipation"],
  10206: [["immunity","thick-fat"],"gluttony"],
  10207: [["stench","weak-armor"],"aftermath"],
  10208: [["iron-fist"],null],
  10209: [["overgrow"],"grassy-surge"],
  10210: [["blaze"],"libero"],
  10211: [["torrent"],"sniper"],
  10212: [["pressure","unnerve"],"mirror-armor"],
  10213: [["swarm","frisk"],"telepathy"],
  10214: [["strong-jaw","shell-armor"],"swift-swim"],
  10215: [["steam-engine","flame-body"],"flash-fire"],
  10216: [["ripen","gluttony"],"hustle"],
  10217: [["ripen","gluttony"],"thick-fat"],
  10218: [["sand-spit","shed-skin"],"sand-veil"],
  10219: [["punk-rock","plus"],"technician"],
  10220: [["flash-fire","white-smoke"],"flame-body"],
  10221: [["healer","anticipation"],"magic-bounce"],
  10222: [["prankster","frisk"],"pickpocket"],
  10223: [["sweet-veil"],"aroma-veil"],
  10224: [["sheer-force"],"heavy-metal"],
  10225: [["light-metal","heavy-metal"],"stalwart"],
  10226: [["unseen-fist"],null],
  10227: [["unseen-fist"],null],
  10228: [["punk-rock","minus"],"technician"],
  10245: [["pressure"],"telepathy"],
  10246: [["pressure"],"telepathy"],
  10247: [["rattled","adaptability"],"mold-breaker"],
  10248: [["swift-swim","adaptability"],"mold-breaker"],
  10249: [["overcoat"],null],
  10250: [["intimidate","anger-point"],"cud-chew"],
  10251: [["intimidate","anger-point"],"cud-chew"],
  10252: [["intimidate","anger-point"],"cud-chew"],
  10253: [["poison-point","water-absorb"],"unaware"],
  10254: [["aroma-veil","gluttony"],"thick-fat"],
  10255: [["serene-grace","run-away"],"rattled"],
  10256: [["zero-to-hero"],null],
  10257: [["friend-guard","cheek-pouch"],"technician"],
  10258: [["commander"],"storm-drain"],
  10259: [["commander"],"storm-drain"],
  10260: [["intimidate","hustle"],"guts"],
  10261: [["intimidate","hustle"],"sheer-force"],
  10262: [["intimidate","hustle"],"sheer-force"],
  10263: [["run-away"],null],
  10272: [["minds-eye"],null],
  10273: [["water-absorb"],null],
  10274: [["mold-breaker"],null],
  10275: [["sturdy"],null],
  10276: [["tera-shell"],null],
  10277: [["teraform-zero"],null],
  10278: [["magic-bounce"],null],
  10279: [["innards-out"],null],
  10280: [["huge-power"],null],
  10281: [["multiscale"],null],
  10282: [["mega-sol"],null],
  10283: [["dragonize"],null],
  10284: [["stalwart"],null],
  10285: [["snow-warning"],null],
  10286: [["mold-breaker"],null],
  10287: [["piercing-drill"],null],
  10288: [["shell-armor"],null],
  10289: [["intimidate"],null],
  10290: [["eelevate"],null],
  10291: [["infiltrator"],null],
  10292: [["bulletproof"],null],
  10293: [["levitate"],null],
  10294: [["protean"],null],
  10295: [["fire-mane"],null],
  10296: [["fairy-aura"],null],
  10297: [["contrary"],null],
  10298: [["tough-claws"],null],
  10299: [["regenerator"],null],
  10300: [["no-guard"],null],
  10301: [[],null],
  10302: [["berserk"],null],
  10303: [["defiant"],null],
  10304: [["electric-surge"],null],
  10305: [["no-guard"],null],
  10306: [["levitate"],null],
  10307: [["sharpness"],null],
  10308: [["contrary"],null],
  10309: [["levitate"],null],
  10310: [["aura-guard"],null],
  10311: [[],null],
  10312: [[],null],
  10313: [["unseen-fist"],null],
  10314: [["trace"],null],
  10315: [["iron-fist"],null],
  10316: [["tough-claws"],null],
  10317: [[],null],
  10318: [[],null],
  10319: [[],null],
  10320: [["spicy-spray"],null],
  10321: [["adaptability"],null],
  10322: [[],null],
  10323: [[],null],
  10324: [[],null],
  10325: [["thermal-exchange"],null],
  10326: [["trace"],null],
  201001: [["levitate"],null],
  201002: [["levitate"],null],
  201003: [["levitate"],null],
  201004: [["levitate"],null],
  201005: [["levitate"],null],
  201006: [["levitate"],null],
  201007: [["levitate"],null],
  201008: [["levitate"],null],
  201009: [["levitate"],null],
  201010: [["levitate"],null],
  201011: [["levitate"],null],
  201012: [["levitate"],null],
  201013: [["levitate"],null],
  201014: [["levitate"],null],
  201015: [["levitate"],null],
  201016: [["levitate"],null],
  201017: [["levitate"],null],
  201018: [["levitate"],null],
  201019: [["levitate"],null],
  201020: [["levitate"],null],
  201021: [["levitate"],null],
  201022: [["levitate"],null],
  201023: [["levitate"],null],
  201024: [["levitate"],null],
  201025: [["levitate"],null],
  201026: [["levitate"],null],
  201027: [["levitate"],null],
  666001: [["shield-dust","compound-eyes"],"friend-guard"],
  666002: [["shield-dust","compound-eyes"],"friend-guard"],
  666003: [["shield-dust","compound-eyes"],"friend-guard"],
  666004: [["shield-dust","compound-eyes"],"friend-guard"],
  666005: [["shield-dust","compound-eyes"],"friend-guard"],
  666006: [["shield-dust","compound-eyes"],"friend-guard"],
  666007: [["shield-dust","compound-eyes"],"friend-guard"],
  666008: [["shield-dust","compound-eyes"],"friend-guard"],
  666009: [["shield-dust","compound-eyes"],"friend-guard"],
  666010: [["shield-dust","compound-eyes"],"friend-guard"],
  666011: [["shield-dust","compound-eyes"],"friend-guard"],
  666012: [["shield-dust","compound-eyes"],"friend-guard"],
  666013: [["shield-dust","compound-eyes"],"friend-guard"],
  666014: [["shield-dust","compound-eyes"],"friend-guard"],
  666015: [["shield-dust","compound-eyes"],"friend-guard"],
  666016: [["shield-dust","compound-eyes"],"friend-guard"],
  666017: [["shield-dust","compound-eyes"],"friend-guard"],
  666018: [["shield-dust","compound-eyes"],"friend-guard"],
  666019: [["shield-dust","compound-eyes"],"friend-guard"],
  666020: [["shield-dust","compound-eyes"],"friend-guard"],
};
